
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.how.module.itf.server.ws.omsorder;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-07-30T16:59:51.787+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "CustomerService",
                      portName = "CustomerServiceHttpPort",
                      targetNamespace = "http://services.customer.interfaces.sinotrans.com",
                      wsdlLocation = "http://oms.hoau.net/services/CustomerService?wsdl",
                      endpointInterface = "com.hoau.how.module.itf.server.ws.omsorder.CustomerServicePortType")
                      
public class CustomerServiceHttpPortImpl implements CustomerServicePortType {

    private static final Logger LOG = Logger.getLogger(CustomerServiceHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.omsorder.CustomerServicePortType#cancelOrder(com.hoau.how.module.itf.server.ws.omsorder.CancelOrderReqModel  in0 )*
     */
    public com.hoau.how.module.itf.server.ws.omsorder.CancelOrderResModel cancelOrder(com.hoau.how.module.itf.server.ws.omsorder.CancelOrderReqModel in0) { 
        LOG.info("Executing operation cancelOrder");
        System.out.println(in0);
        try {
            com.hoau.how.module.itf.server.ws.omsorder.CancelOrderResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.omsorder.CustomerServicePortType#cutomerOrder(com.hoau.how.module.itf.server.ws.omsorder.CustOrderReqModel  in0 )*
     */
    public com.hoau.how.module.itf.server.ws.omsorder.CustOrderResModel cutomerOrder(com.hoau.how.module.itf.server.ws.omsorder.CustOrderReqModel in0) { 
        LOG.info("Executing operation cutomerOrder");
        System.out.println(in0);
        try {
            com.hoau.how.module.itf.server.ws.omsorder.CustOrderResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.omsorder.CustomerServicePortType#saveNetOrder(com.hoau.how.module.itf.server.ws.omsorder.EiNetOrderReqModel  in0 )*
     */
    public com.hoau.how.module.itf.server.ws.omsorder.EiNetOrderReqModel saveNetOrder(com.hoau.how.module.itf.server.ws.omsorder.EiNetOrderReqModel in0) { 
        LOG.info("Executing operation saveNetOrder");
        try {
            com.hoau.how.module.itf.server.ws.omsorder.EiNetOrderReqModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.omsorder.CustomerServicePortType#modifyOrder(com.hoau.how.module.itf.server.ws.omsorder.CustOrderReqModel  in0 )*
     */
    public com.hoau.how.module.itf.server.ws.omsorder.CustOrderResModel modifyOrder(com.hoau.how.module.itf.server.ws.omsorder.CustOrderReqModel in0) { 
        LOG.info("Executing operation modifyOrder");
        System.out.println(in0);
        try {
            com.hoau.how.module.itf.server.ws.omsorder.CustOrderResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.omsorder.CustomerServicePortType#updateNetOrder(com.hoau.how.module.itf.server.ws.omsorder.EiNetOrderReqModel  in0 )*
     */
    public com.hoau.how.module.itf.server.ws.omsorder.EiNetOrderReq updateNetOrder(com.hoau.how.module.itf.server.ws.omsorder.EiNetOrderReqModel in0) { 
        LOG.info("Executing operation updateNetOrder");
        System.out.println(in0);
        try {
            com.hoau.how.module.itf.server.ws.omsorder.EiNetOrderReq _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.omsorder.CustomerServicePortType#trackOrder(com.hoau.how.module.itf.server.ws.omsorder.TrackOrderReqModel  in0 )*
     */
    public com.hoau.how.module.itf.server.ws.omsorder.TrackOrderResModel trackOrder(com.hoau.how.module.itf.server.ws.omsorder.TrackOrderReqModel in0) { 
        LOG.info("Executing operation trackOrder");
        System.out.println(in0);
        try {
            com.hoau.how.module.itf.server.ws.omsorder.TrackOrderResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.omsorder.CustomerServicePortType#queryOrder(com.hoau.how.module.itf.server.ws.omsorder.QueryOrderReqModel  in0 )*
     */
    public com.hoau.how.module.itf.server.ws.omsorder.QueryOrderResModel queryOrder(com.hoau.how.module.itf.server.ws.omsorder.QueryOrderReqModel in0) { 
        LOG.info("Executing operation queryOrder");
        System.out.println(in0);
        try {
            com.hoau.how.module.itf.server.ws.omsorder.QueryOrderResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
