package com.hoau.how.module.common.shared.domain;

/**
 *
 * @author 徐俊
 * @date 2015年6月16日
 */
public class CompanyEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.id
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.area
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.short_name
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.standard_code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String standardCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.extension_code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String extensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.is_effective
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String isEffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.is_controlled
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String isControlled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.is_drd
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String isDrd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.company_type
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.belongs_company
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String belongsCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.parent_company
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String parentCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.distance_logo
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String distanceLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.is_virtual
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String isVirtual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.name
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.name_code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private Double nameCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.legal_representative
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String legalRepresentative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.business_scope
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String businessScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.business_type
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.license_copies_number
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private Double licenseCopiesNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.operation_mode
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String operationMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.operation_limit
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private Double operationLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.province
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.city
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.district
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.street
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.address
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.phone
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.fax
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.zip
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.registered_capital
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private Double registeredCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.test_company
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String testCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.point_x
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String pointX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.point_y
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String pointY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hoau_company.contactor
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    private String contactor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.id
     *
     * @return the value of hoau_company.id
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.id
     *
     * @param id the value for hoau_company.id
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.area
     *
     * @return the value of hoau_company.area
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.area
     *
     * @param area the value for hoau_company.area
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.code
     *
     * @return the value of hoau_company.code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.code
     *
     * @param code the value for hoau_company.code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.short_name
     *
     * @return the value of hoau_company.short_name
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.short_name
     *
     * @param shortName the value for hoau_company.short_name
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.standard_code
     *
     * @return the value of hoau_company.standard_code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getStandardCode() {
        return standardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.standard_code
     *
     * @param standardCode the value for hoau_company.standard_code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setStandardCode(String standardCode) {
        this.standardCode = standardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.extension_code
     *
     * @return the value of hoau_company.extension_code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getExtensionCode() {
        return extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.extension_code
     *
     * @param extensionCode the value for hoau_company.extension_code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setExtensionCode(String extensionCode) {
        this.extensionCode = extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.is_effective
     *
     * @return the value of hoau_company.is_effective
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.is_effective
     *
     * @param isEffective the value for hoau_company.is_effective
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setIsEffective(String isEffective) {
        this.isEffective = isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.is_controlled
     *
     * @return the value of hoau_company.is_controlled
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getIsControlled() {
        return isControlled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.is_controlled
     *
     * @param isControlled the value for hoau_company.is_controlled
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setIsControlled(String isControlled) {
        this.isControlled = isControlled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.is_drd
     *
     * @return the value of hoau_company.is_drd
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getIsDrd() {
        return isDrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.is_drd
     *
     * @param isDrd the value for hoau_company.is_drd
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setIsDrd(String isDrd) {
        this.isDrd = isDrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.company_type
     *
     * @return the value of hoau_company.company_type
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.company_type
     *
     * @param companyType the value for hoau_company.company_type
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.belongs_company
     *
     * @return the value of hoau_company.belongs_company
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getBelongsCompany() {
        return belongsCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.belongs_company
     *
     * @param belongsCompany the value for hoau_company.belongs_company
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setBelongsCompany(String belongsCompany) {
        this.belongsCompany = belongsCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.parent_company
     *
     * @return the value of hoau_company.parent_company
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getParentCompany() {
        return parentCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.parent_company
     *
     * @param parentCompany the value for hoau_company.parent_company
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setParentCompany(String parentCompany) {
        this.parentCompany = parentCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.distance_logo
     *
     * @return the value of hoau_company.distance_logo
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getDistanceLogo() {
        return distanceLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.distance_logo
     *
     * @param distanceLogo the value for hoau_company.distance_logo
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setDistanceLogo(String distanceLogo) {
        this.distanceLogo = distanceLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.is_virtual
     *
     * @return the value of hoau_company.is_virtual
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getIsVirtual() {
        return isVirtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.is_virtual
     *
     * @param isVirtual the value for hoau_company.is_virtual
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setIsVirtual(String isVirtual) {
        this.isVirtual = isVirtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.name
     *
     * @return the value of hoau_company.name
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.name
     *
     * @param name the value for hoau_company.name
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.name_code
     *
     * @return the value of hoau_company.name_code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public Double getNameCode() {
        return nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.name_code
     *
     * @param nameCode the value for hoau_company.name_code
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setNameCode(Double nameCode) {
        this.nameCode = nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.legal_representative
     *
     * @return the value of hoau_company.legal_representative
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getLegalRepresentative() {
        return legalRepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.legal_representative
     *
     * @param legalRepresentative the value for hoau_company.legal_representative
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setLegalRepresentative(String legalRepresentative) {
        this.legalRepresentative = legalRepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.business_scope
     *
     * @return the value of hoau_company.business_scope
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.business_scope
     *
     * @param businessScope the value for hoau_company.business_scope
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.business_type
     *
     * @return the value of hoau_company.business_type
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.business_type
     *
     * @param businessType the value for hoau_company.business_type
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.license_copies_number
     *
     * @return the value of hoau_company.license_copies_number
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public Double getLicenseCopiesNumber() {
        return licenseCopiesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.license_copies_number
     *
     * @param licenseCopiesNumber the value for hoau_company.license_copies_number
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setLicenseCopiesNumber(Double licenseCopiesNumber) {
        this.licenseCopiesNumber = licenseCopiesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.operation_mode
     *
     * @return the value of hoau_company.operation_mode
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getOperationMode() {
        return operationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.operation_mode
     *
     * @param operationMode the value for hoau_company.operation_mode
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setOperationMode(String operationMode) {
        this.operationMode = operationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.operation_limit
     *
     * @return the value of hoau_company.operation_limit
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public Double getOperationLimit() {
        return operationLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.operation_limit
     *
     * @param operationLimit the value for hoau_company.operation_limit
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setOperationLimit(Double operationLimit) {
        this.operationLimit = operationLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.province
     *
     * @return the value of hoau_company.province
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.province
     *
     * @param province the value for hoau_company.province
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.city
     *
     * @return the value of hoau_company.city
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.city
     *
     * @param city the value for hoau_company.city
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.district
     *
     * @return the value of hoau_company.district
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.district
     *
     * @param district the value for hoau_company.district
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.street
     *
     * @return the value of hoau_company.street
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.street
     *
     * @param street the value for hoau_company.street
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.address
     *
     * @return the value of hoau_company.address
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.address
     *
     * @param address the value for hoau_company.address
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.phone
     *
     * @return the value of hoau_company.phone
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.phone
     *
     * @param phone the value for hoau_company.phone
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.fax
     *
     * @return the value of hoau_company.fax
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.fax
     *
     * @param fax the value for hoau_company.fax
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.zip
     *
     * @return the value of hoau_company.zip
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.zip
     *
     * @param zip the value for hoau_company.zip
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.registered_capital
     *
     * @return the value of hoau_company.registered_capital
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public Double getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.registered_capital
     *
     * @param registeredCapital the value for hoau_company.registered_capital
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setRegisteredCapital(Double registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.test_company
     *
     * @return the value of hoau_company.test_company
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getTestCompany() {
        return testCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.test_company
     *
     * @param testCompany the value for hoau_company.test_company
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setTestCompany(String testCompany) {
        this.testCompany = testCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.point_x
     *
     * @return the value of hoau_company.point_x
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getPointX() {
        return pointX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.point_x
     *
     * @param pointX the value for hoau_company.point_x
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setPointX(String pointX) {
        this.pointX = pointX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.point_y
     *
     * @return the value of hoau_company.point_y
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getPointY() {
        return pointY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.point_y
     *
     * @param pointY the value for hoau_company.point_y
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setPointY(String pointY) {
        this.pointY = pointY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hoau_company.contactor
     *
     * @return the value of hoau_company.contactor
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public String getContactor() {
        return contactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hoau_company.contactor
     *
     * @param contactor the value for hoau_company.contactor
     *
     * @mbggenerated Tue Jun 16 16:27:47 CST 2015
     */
    public void setContactor(String contactor) {
        this.contactor = contactor;
    }
}