package com.hoau.mhow.invokews.server.ws.waybilldetail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-06-16T18:07:21.232+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.szzc.com.cn/services/WptServices", name = "WptServices")
@XmlSeeAlso({ObjectFactory.class})
public interface WptServices {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWptYdInfo", targetNamespace = "http://www.szzc.com.cn/services/WptServices", className = "com.hoau.mhow.invokews.server.ws.waybilldetail.GetWptYdInfo")
    @WebMethod
    @ResponseWrapper(localName = "getWptYdInfoResponse", targetNamespace = "http://www.szzc.com.cn/services/WptServices", className = "com.hoau.mhow.invokews.server.ws.waybilldetail.GetWptYdInfoResponse")
    public java.util.List<com.hoau.mhow.invokews.server.ws.waybilldetail.WptYdInfo> getWptYdInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );
}
