
package com.hoau.mhow.invokews.server.ws.waybilldetail;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-06-16T18:07:21.237+08:00
 * Generated source version: 3.0.1
 * 
 */
 
public class WptServices_WptServicesPort_Server{

    protected WptServices_WptServicesPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new WptServicesPortImpl();
        String address = "http://10.39.109.29:8080/services/WptServices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new WptServices_WptServicesPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
