package com.hoau.mhow.module.bse.api.shared.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class NetOrderEntity implements Serializable{
	private static final long serialVersionUID = 8450576987472209778L;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long einoId;
    private int number;
    private String shipperDistrict;
	private String consigneeDistrict;
	private String validate;
	private String companyMsg;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_contract_no
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoContractNo;
    
    private String einoOrderNo;
    
    private String einoConsigneeBranchesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_custom_ebcu_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoCustomEbcuNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_ebcc_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoEbccName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_order_date
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Date einoOrderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_status
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_ebsp_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoShipperEbspNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_ebsa_contact
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoShipperEbsaContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_ebsa_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoShipperEbsaTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_ebsa_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoShipperEbsaAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_ebpl_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long einoShipperEbplId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_ebpl_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoShipperEbplNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebsp_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoConsigneeEbspNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebsa_contact
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoConsigneeEbsaContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebsa_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoConsigneeEbsaTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebsa_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoConsigneeEbsaAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebrg_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long einoConsigneeEbrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebrg_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoConsigneeEbrgNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebpl_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long einoConsigneeEbplId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebpl_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoConsigneeEbplNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_remark
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_trans_no
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoTransNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_orign
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoOrign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_product_type_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoProductTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_esco_second_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoEscoSecondCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_esco_second_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoEscoSecondName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_ebpv_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long einoShipperEbpvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_ebpv_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoShipperEbpvName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_ebsa_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoShipperEbsaMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebpv_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long einoConsigneeEbpvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebpv_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoConsigneeEbpvName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebsa_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoConsigneeEbsaMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_exception_type
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoExceptionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_ebsa_area_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoShipperEbsaAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_consignee_ebsa_area_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoConsigneeEbsaAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_door_canvass
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoDoorCanvass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_payment_method
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoPaymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_method
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoShipperMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_sign_back
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoSignBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_package
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_coll_delivery_amount
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private BigDecimal einoCollDeliveryAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_coll_delivery_charge
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private BigDecimal einoCollDeliveryCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_sms_notif
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoSmsNotif;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_insurance
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Double einoInsurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_insurance_charge
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private BigDecimal einoInsuranceCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_trans_charge
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private BigDecimal einoTransCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_charge_total
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private BigDecimal einoChargeTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_ebcc_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long einoEbccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_cargo_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoCargoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_total_volume
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Double einoTotalVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_number
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long einoNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_total_weight
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Double einoTotalWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_is_import
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Short einoIsImport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_invited_status
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Short einoInvitedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipping_date
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Date einoShippingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_area_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long einoShipperAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_shipper_area_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoShipperAreaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_batch_order
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Short einoBatchOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ei_net_order.eino_second_district
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String einoSecondDistrict;
    
    private String einoCustomerCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_id
     *
     * @return the value of ei_net_order.eino_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEinoId() {
        return einoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_id
     *
     * @param einoId the value for ei_net_order.eino_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoId(Long einoId) {
        this.einoId = einoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_contract_no
     *
     * @return the value of ei_net_order.eino_contract_no
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoContractNo() {
        return einoContractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_contract_no
     *
     * @param einoContractNo the value for ei_net_order.eino_contract_no
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoContractNo(String einoContractNo) {
        this.einoContractNo = einoContractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_custom_ebcu_name_cn
     *
     * @return the value of ei_net_order.eino_custom_ebcu_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoCustomEbcuNameCn() {
        return einoCustomEbcuNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_custom_ebcu_name_cn
     *
     * @param einoCustomEbcuNameCn the value for ei_net_order.eino_custom_ebcu_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoCustomEbcuNameCn(String einoCustomEbcuNameCn) {
        this.einoCustomEbcuNameCn = einoCustomEbcuNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_ebcc_name
     *
     * @return the value of ei_net_order.eino_ebcc_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoEbccName() {
        return einoEbccName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_ebcc_name
     *
     * @param einoEbccName the value for ei_net_order.eino_ebcc_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoEbccName(String einoEbccName) {
        this.einoEbccName = einoEbccName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_order_date
     *
     * @return the value of ei_net_order.eino_order_date
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Date getEinoOrderDate() {
        return einoOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_order_date
     *
     * @param einoOrderDate the value for ei_net_order.eino_order_date
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoOrderDate(Date einoOrderDate) {
        this.einoOrderDate = einoOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_status
     *
     * @return the value of ei_net_order.eino_status
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoStatus() {
        return einoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_status
     *
     * @param einoStatus the value for ei_net_order.eino_status
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoStatus(String einoStatus) {
        this.einoStatus = einoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_ebsp_name_cn
     *
     * @return the value of ei_net_order.eino_shipper_ebsp_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoShipperEbspNameCn() {
        return einoShipperEbspNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_ebsp_name_cn
     *
     * @param einoShipperEbspNameCn the value for ei_net_order.eino_shipper_ebsp_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperEbspNameCn(String einoShipperEbspNameCn) {
        this.einoShipperEbspNameCn = einoShipperEbspNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_ebsa_contact
     *
     * @return the value of ei_net_order.eino_shipper_ebsa_contact
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoShipperEbsaContact() {
        return einoShipperEbsaContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_ebsa_contact
     *
     * @param einoShipperEbsaContact the value for ei_net_order.eino_shipper_ebsa_contact
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperEbsaContact(String einoShipperEbsaContact) {
        this.einoShipperEbsaContact = einoShipperEbsaContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_ebsa_tel
     *
     * @return the value of ei_net_order.eino_shipper_ebsa_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoShipperEbsaTel() {
        return einoShipperEbsaTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_ebsa_tel
     *
     * @param einoShipperEbsaTel the value for ei_net_order.eino_shipper_ebsa_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperEbsaTel(String einoShipperEbsaTel) {
        this.einoShipperEbsaTel = einoShipperEbsaTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_ebsa_address
     *
     * @return the value of ei_net_order.eino_shipper_ebsa_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoShipperEbsaAddress() {
        return einoShipperEbsaAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_ebsa_address
     *
     * @param einoShipperEbsaAddress the value for ei_net_order.eino_shipper_ebsa_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperEbsaAddress(String einoShipperEbsaAddress) {
        this.einoShipperEbsaAddress = einoShipperEbsaAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_ebpl_id
     *
     * @return the value of ei_net_order.eino_shipper_ebpl_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEinoShipperEbplId() {
        return einoShipperEbplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_ebpl_id
     *
     * @param einoShipperEbplId the value for ei_net_order.eino_shipper_ebpl_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperEbplId(Long einoShipperEbplId) {
        this.einoShipperEbplId = einoShipperEbplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_ebpl_name_cn
     *
     * @return the value of ei_net_order.eino_shipper_ebpl_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoShipperEbplNameCn() {
        return einoShipperEbplNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_ebpl_name_cn
     *
     * @param einoShipperEbplNameCn the value for ei_net_order.eino_shipper_ebpl_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperEbplNameCn(String einoShipperEbplNameCn) {
        this.einoShipperEbplNameCn = einoShipperEbplNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebsp_name_cn
     *
     * @return the value of ei_net_order.eino_consignee_ebsp_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoConsigneeEbspNameCn() {
        return einoConsigneeEbspNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebsp_name_cn
     *
     * @param einoConsigneeEbspNameCn the value for ei_net_order.eino_consignee_ebsp_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbspNameCn(String einoConsigneeEbspNameCn) {
        this.einoConsigneeEbspNameCn = einoConsigneeEbspNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebsa_contact
     *
     * @return the value of ei_net_order.eino_consignee_ebsa_contact
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoConsigneeEbsaContact() {
        return einoConsigneeEbsaContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebsa_contact
     *
     * @param einoConsigneeEbsaContact the value for ei_net_order.eino_consignee_ebsa_contact
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbsaContact(String einoConsigneeEbsaContact) {
        this.einoConsigneeEbsaContact = einoConsigneeEbsaContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebsa_tel
     *
     * @return the value of ei_net_order.eino_consignee_ebsa_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoConsigneeEbsaTel() {
        return einoConsigneeEbsaTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebsa_tel
     *
     * @param einoConsigneeEbsaTel the value for ei_net_order.eino_consignee_ebsa_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbsaTel(String einoConsigneeEbsaTel) {
        this.einoConsigneeEbsaTel = einoConsigneeEbsaTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebsa_address
     *
     * @return the value of ei_net_order.eino_consignee_ebsa_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoConsigneeEbsaAddress() {
        return einoConsigneeEbsaAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebsa_address
     *
     * @param einoConsigneeEbsaAddress the value for ei_net_order.eino_consignee_ebsa_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbsaAddress(String einoConsigneeEbsaAddress) {
        this.einoConsigneeEbsaAddress = einoConsigneeEbsaAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebrg_id
     *
     * @return the value of ei_net_order.eino_consignee_ebrg_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEinoConsigneeEbrgId() {
        return einoConsigneeEbrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebrg_id
     *
     * @param einoConsigneeEbrgId the value for ei_net_order.eino_consignee_ebrg_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbrgId(Long einoConsigneeEbrgId) {
        this.einoConsigneeEbrgId = einoConsigneeEbrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebrg_name_cn
     *
     * @return the value of ei_net_order.eino_consignee_ebrg_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoConsigneeEbrgNameCn() {
        return einoConsigneeEbrgNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebrg_name_cn
     *
     * @param einoConsigneeEbrgNameCn the value for ei_net_order.eino_consignee_ebrg_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbrgNameCn(String einoConsigneeEbrgNameCn) {
        this.einoConsigneeEbrgNameCn = einoConsigneeEbrgNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebpl_id
     *
     * @return the value of ei_net_order.eino_consignee_ebpl_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEinoConsigneeEbplId() {
        return einoConsigneeEbplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebpl_id
     *
     * @param einoConsigneeEbplId the value for ei_net_order.eino_consignee_ebpl_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbplId(Long einoConsigneeEbplId) {
        this.einoConsigneeEbplId = einoConsigneeEbplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebpl_name_cn
     *
     * @return the value of ei_net_order.eino_consignee_ebpl_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoConsigneeEbplNameCn() {
        return einoConsigneeEbplNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebpl_name_cn
     *
     * @param einoConsigneeEbplNameCn the value for ei_net_order.eino_consignee_ebpl_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbplNameCn(String einoConsigneeEbplNameCn) {
        this.einoConsigneeEbplNameCn = einoConsigneeEbplNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_remark
     *
     * @return the value of ei_net_order.eino_remark
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoRemark() {
        return einoRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_remark
     *
     * @param einoRemark the value for ei_net_order.eino_remark
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoRemark(String einoRemark) {
        this.einoRemark = einoRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.creator
     *
     * @return the value of ei_net_order.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.creator
     *
     * @param creator the value for ei_net_order.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.create_time
     *
     * @return the value of ei_net_order.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.create_time
     *
     * @param createTime the value for ei_net_order.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.modifier
     *
     * @return the value of ei_net_order.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.modifier
     *
     * @param modifier the value for ei_net_order.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.modify_time
     *
     * @return the value of ei_net_order.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.modify_time
     *
     * @param modifyTime the value for ei_net_order.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_trans_no
     *
     * @return the value of ei_net_order.eino_trans_no
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoTransNo() {
        return einoTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_trans_no
     *
     * @param einoTransNo the value for ei_net_order.eino_trans_no
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoTransNo(String einoTransNo) {
        this.einoTransNo = einoTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_orign
     *
     * @return the value of ei_net_order.eino_orign
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoOrign() {
        return einoOrign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_orign
     *
     * @param einoOrign the value for ei_net_order.eino_orign
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoOrign(String einoOrign) {
        this.einoOrign = einoOrign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_product_type_name
     *
     * @return the value of ei_net_order.eino_product_type_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoProductTypeName() {
        return einoProductTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_product_type_name
     *
     * @param einoProductTypeName the value for ei_net_order.eino_product_type_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoProductTypeName(String einoProductTypeName) {
        this.einoProductTypeName = einoProductTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_esco_second_code
     *
     * @return the value of ei_net_order.eino_esco_second_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoEscoSecondCode() {
        return einoEscoSecondCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_esco_second_code
     *
     * @param einoEscoSecondCode the value for ei_net_order.eino_esco_second_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoEscoSecondCode(String einoEscoSecondCode) {
        this.einoEscoSecondCode = einoEscoSecondCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_esco_second_name
     *
     * @return the value of ei_net_order.eino_esco_second_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoEscoSecondName() {
        return einoEscoSecondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_esco_second_name
     *
     * @param einoEscoSecondName the value for ei_net_order.eino_esco_second_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoEscoSecondName(String einoEscoSecondName) {
        this.einoEscoSecondName = einoEscoSecondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_ebpv_id
     *
     * @return the value of ei_net_order.eino_shipper_ebpv_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEinoShipperEbpvId() {
        return einoShipperEbpvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_ebpv_id
     *
     * @param einoShipperEbpvId the value for ei_net_order.eino_shipper_ebpv_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperEbpvId(Long einoShipperEbpvId) {
        this.einoShipperEbpvId = einoShipperEbpvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_ebpv_name
     *
     * @return the value of ei_net_order.eino_shipper_ebpv_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoShipperEbpvName() {
        return einoShipperEbpvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_ebpv_name
     *
     * @param einoShipperEbpvName the value for ei_net_order.eino_shipper_ebpv_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperEbpvName(String einoShipperEbpvName) {
        this.einoShipperEbpvName = einoShipperEbpvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_ebsa_mobile
     *
     * @return the value of ei_net_order.eino_shipper_ebsa_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoShipperEbsaMobile() {
        return einoShipperEbsaMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_ebsa_mobile
     *
     * @param einoShipperEbsaMobile the value for ei_net_order.eino_shipper_ebsa_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperEbsaMobile(String einoShipperEbsaMobile) {
        this.einoShipperEbsaMobile = einoShipperEbsaMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebpv_id
     *
     * @return the value of ei_net_order.eino_consignee_ebpv_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEinoConsigneeEbpvId() {
        return einoConsigneeEbpvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebpv_id
     *
     * @param einoConsigneeEbpvId the value for ei_net_order.eino_consignee_ebpv_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbpvId(Long einoConsigneeEbpvId) {
        this.einoConsigneeEbpvId = einoConsigneeEbpvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebpv_name
     *
     * @return the value of ei_net_order.eino_consignee_ebpv_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoConsigneeEbpvName() {
        return einoConsigneeEbpvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebpv_name
     *
     * @param einoConsigneeEbpvName the value for ei_net_order.eino_consignee_ebpv_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbpvName(String einoConsigneeEbpvName) {
        this.einoConsigneeEbpvName = einoConsigneeEbpvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebsa_mobile
     *
     * @return the value of ei_net_order.eino_consignee_ebsa_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoConsigneeEbsaMobile() {
        return einoConsigneeEbsaMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebsa_mobile
     *
     * @param einoConsigneeEbsaMobile the value for ei_net_order.eino_consignee_ebsa_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbsaMobile(String einoConsigneeEbsaMobile) {
        this.einoConsigneeEbsaMobile = einoConsigneeEbsaMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_exception_type
     *
     * @return the value of ei_net_order.eino_exception_type
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoExceptionType() {
        return einoExceptionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_exception_type
     *
     * @param einoExceptionType the value for ei_net_order.eino_exception_type
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoExceptionType(String einoExceptionType) {
        this.einoExceptionType = einoExceptionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_ebsa_area_code
     *
     * @return the value of ei_net_order.eino_shipper_ebsa_area_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoShipperEbsaAreaCode() {
        return einoShipperEbsaAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_ebsa_area_code
     *
     * @param einoShipperEbsaAreaCode the value for ei_net_order.eino_shipper_ebsa_area_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperEbsaAreaCode(String einoShipperEbsaAreaCode) {
        this.einoShipperEbsaAreaCode = einoShipperEbsaAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_consignee_ebsa_area_code
     *
     * @return the value of ei_net_order.eino_consignee_ebsa_area_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoConsigneeEbsaAreaCode() {
        return einoConsigneeEbsaAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_consignee_ebsa_area_code
     *
     * @param einoConsigneeEbsaAreaCode the value for ei_net_order.eino_consignee_ebsa_area_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoConsigneeEbsaAreaCode(String einoConsigneeEbsaAreaCode) {
        this.einoConsigneeEbsaAreaCode = einoConsigneeEbsaAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_door_canvass
     *
     * @return the value of ei_net_order.eino_door_canvass
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoDoorCanvass() {
        return einoDoorCanvass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_door_canvass
     *
     * @param einoDoorCanvass the value for ei_net_order.eino_door_canvass
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoDoorCanvass(String einoDoorCanvass) {
        this.einoDoorCanvass = einoDoorCanvass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_payment_method
     *
     * @return the value of ei_net_order.eino_payment_method
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoPaymentMethod() {
        return einoPaymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_payment_method
     *
     * @param einoPaymentMethod the value for ei_net_order.eino_payment_method
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoPaymentMethod(String einoPaymentMethod) {
        this.einoPaymentMethod = einoPaymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_method
     *
     * @return the value of ei_net_order.eino_shipper_method
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoShipperMethod() {
        return einoShipperMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_method
     *
     * @param einoShipperMethod the value for ei_net_order.eino_shipper_method
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperMethod(String einoShipperMethod) {
        this.einoShipperMethod = einoShipperMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_sign_back
     *
     * @return the value of ei_net_order.eino_sign_back
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoSignBack() {
        return einoSignBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_sign_back
     *
     * @param einoSignBack the value for ei_net_order.eino_sign_back
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoSignBack(String einoSignBack) {
        this.einoSignBack = einoSignBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_package
     *
     * @return the value of ei_net_order.eino_package
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoPackage() {
        return einoPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_package
     *
     * @param einoPackage the value for ei_net_order.eino_package
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoPackage(String einoPackage) {
        this.einoPackage = einoPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_coll_delivery_amount
     *
     * @return the value of ei_net_order.eino_coll_delivery_amount
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public BigDecimal getEinoCollDeliveryAmount() {
        return einoCollDeliveryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_coll_delivery_amount
     *
     * @param einoCollDeliveryAmount the value for ei_net_order.eino_coll_delivery_amount
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoCollDeliveryAmount(BigDecimal einoCollDeliveryAmount) {
        this.einoCollDeliveryAmount = einoCollDeliveryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_coll_delivery_charge
     *
     * @return the value of ei_net_order.eino_coll_delivery_charge
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public BigDecimal getEinoCollDeliveryCharge() {
        return einoCollDeliveryCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_coll_delivery_charge
     *
     * @param einoCollDeliveryCharge the value for ei_net_order.eino_coll_delivery_charge
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoCollDeliveryCharge(BigDecimal einoCollDeliveryCharge) {
        this.einoCollDeliveryCharge = einoCollDeliveryCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_sms_notif
     *
     * @return the value of ei_net_order.eino_sms_notif
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoSmsNotif() {
        return einoSmsNotif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_sms_notif
     *
     * @param einoSmsNotif the value for ei_net_order.eino_sms_notif
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoSmsNotif(String einoSmsNotif) {
        this.einoSmsNotif = einoSmsNotif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_insurance
     *
     * @return the value of ei_net_order.eino_insurance
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Double getEinoInsurance() {
        return einoInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_insurance
     *
     * @param einoInsurance the value for ei_net_order.eino_insurance
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoInsurance(Double einoInsurance) {
        this.einoInsurance = einoInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_insurance_charge
     *
     * @return the value of ei_net_order.eino_insurance_charge
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public BigDecimal getEinoInsuranceCharge() {
        return einoInsuranceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_insurance_charge
     *
     * @param einoInsuranceCharge the value for ei_net_order.eino_insurance_charge
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoInsuranceCharge(BigDecimal einoInsuranceCharge) {
        this.einoInsuranceCharge = einoInsuranceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_trans_charge
     *
     * @return the value of ei_net_order.eino_trans_charge
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public BigDecimal getEinoTransCharge() {
        return einoTransCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_trans_charge
     *
     * @param einoTransCharge the value for ei_net_order.eino_trans_charge
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoTransCharge(BigDecimal einoTransCharge) {
        this.einoTransCharge = einoTransCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_charge_total
     *
     * @return the value of ei_net_order.eino_charge_total
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public BigDecimal getEinoChargeTotal() {
        return einoChargeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_charge_total
     *
     * @param einoChargeTotal the value for ei_net_order.eino_charge_total
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoChargeTotal(BigDecimal einoChargeTotal) {
        this.einoChargeTotal = einoChargeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_ebcc_id
     *
     * @return the value of ei_net_order.eino_ebcc_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEinoEbccId() {
        return einoEbccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_ebcc_id
     *
     * @param einoEbccId the value for ei_net_order.eino_ebcc_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoEbccId(Long einoEbccId) {
        this.einoEbccId = einoEbccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_cargo_name
     *
     * @return the value of ei_net_order.eino_cargo_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoCargoName() {
        return einoCargoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_cargo_name
     *
     * @param einoCargoName the value for ei_net_order.eino_cargo_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoCargoName(String einoCargoName) {
        this.einoCargoName = einoCargoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_total_volume
     *
     * @return the value of ei_net_order.eino_total_volume
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Double getEinoTotalVolume() {
        return einoTotalVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_total_volume
     *
     * @param einoTotalVolume the value for ei_net_order.eino_total_volume
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoTotalVolume(Double einoTotalVolume) {
        this.einoTotalVolume = einoTotalVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_number
     *
     * @return the value of ei_net_order.eino_number
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEinoNumber() {
        return einoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_number
     *
     * @param einoNumber the value for ei_net_order.eino_number
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoNumber(Long einoNumber) {
        this.einoNumber = einoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_total_weight
     *
     * @return the value of ei_net_order.eino_total_weight
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Double getEinoTotalWeight() {
        return einoTotalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_total_weight
     *
     * @param einoTotalWeight the value for ei_net_order.eino_total_weight
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoTotalWeight(Double einoTotalWeight) {
        this.einoTotalWeight = einoTotalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_is_import
     *
     * @return the value of ei_net_order.eino_is_import
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Short getEinoIsImport() {
        return einoIsImport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_is_import
     *
     * @param einoIsImport the value for ei_net_order.eino_is_import
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoIsImport(Short einoIsImport) {
        this.einoIsImport = einoIsImport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_invited_status
     *
     * @return the value of ei_net_order.eino_invited_status
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Short getEinoInvitedStatus() {
        return einoInvitedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_invited_status
     *
     * @param einoInvitedStatus the value for ei_net_order.eino_invited_status
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoInvitedStatus(Short einoInvitedStatus) {
        this.einoInvitedStatus = einoInvitedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipping_date
     *
     * @return the value of ei_net_order.eino_shipping_date
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Date getEinoShippingDate() {
        return einoShippingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipping_date
     *
     * @param einoShippingDate the value for ei_net_order.eino_shipping_date
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShippingDate(Date einoShippingDate) {
        this.einoShippingDate = einoShippingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_area_id
     *
     * @return the value of ei_net_order.eino_shipper_area_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEinoShipperAreaId() {
        return einoShipperAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_area_id
     *
     * @param einoShipperAreaId the value for ei_net_order.eino_shipper_area_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperAreaId(Long einoShipperAreaId) {
        this.einoShipperAreaId = einoShipperAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_shipper_area_name
     *
     * @return the value of ei_net_order.eino_shipper_area_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoShipperAreaName() {
        return einoShipperAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_shipper_area_name
     *
     * @param einoShipperAreaName the value for ei_net_order.eino_shipper_area_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoShipperAreaName(String einoShipperAreaName) {
        this.einoShipperAreaName = einoShipperAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_batch_order
     *
     * @return the value of ei_net_order.eino_batch_order
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Short getEinoBatchOrder() {
        return einoBatchOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_batch_order
     *
     * @param einoBatchOrder the value for ei_net_order.eino_batch_order
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoBatchOrder(Short einoBatchOrder) {
        this.einoBatchOrder = einoBatchOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ei_net_order.eino_second_district
     *
     * @return the value of ei_net_order.eino_second_district
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEinoSecondDistrict() {
        return einoSecondDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ei_net_order.eino_second_district
     *
     * @param einoSecondDistrict the value for ei_net_order.eino_second_district
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEinoSecondDistrict(String einoSecondDistrict) {
        this.einoSecondDistrict = einoSecondDistrict;
    }

	public int getNumber() {
		return number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public String getShipperDistrict() {
		return shipperDistrict;
	}

	public void setShipperDistrict(String shipperDistrict) {
		this.shipperDistrict = shipperDistrict;
	}

	public String getConsigneeDistrict() {
		return consigneeDistrict;
	}

	public void setConsigneeDistrict(String consigneeDistrict) {
		this.consigneeDistrict = consigneeDistrict;
	}

	public String getValidate() {
		return validate;
	}

	public void setValidate(String validate) {
		this.validate = validate;
	}

	public String getCompanyMsg() {
		return companyMsg;
	}

	public void setCompanyMsg(String companyMsg) {
		this.companyMsg = companyMsg;
	}

	public String getEinoCustomerCode() {
		return einoCustomerCode;
	}

	public void setEinoCustomerCode(String einoCustomerCode) {
		this.einoCustomerCode = einoCustomerCode;
	}

	public String getEinoOrderNo() {
		return einoOrderNo;
	}

	public void setEinoOrderNo(String einoOrderNo) {
		this.einoOrderNo = einoOrderNo;
	}

	public String getEinoConsigneeBranchesName() {
		return einoConsigneeBranchesName;
	}

	public void setEinoConsigneeBranchesName(String einoConsigneeBranchesName) {
		this.einoConsigneeBranchesName = einoConsigneeBranchesName;
	}
}