
package com.hoau.wechat.ws.wt;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-10-26T17:18:20.121+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class DistrictServicePortType_DistrictServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.district.interfaces.sinotrans.com", "DistrictService");

    private DistrictServicePortType_DistrictServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DistrictService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DistrictService ss = new DistrictService(wsdlURL, SERVICE_NAME);
        DistrictServicePortType port = ss.getDistrictServiceHttpPort();  
        
        {
        System.out.println("Invoking queryProvince...");
        com.hoau.wechat.ws.wt.ArrayOfDistrictModel _queryProvince__return = port.queryProvince();
        System.out.println("queryProvince.result=" + _queryProvince__return);


        }
        {
        System.out.println("Invoking queryCityByProvince...");
        java.lang.String _queryCityByProvince_in0 = "";
        com.hoau.wechat.ws.wt.ArrayOfDistrictModel _queryCityByProvince__return = port.queryCityByProvince(_queryCityByProvince_in0);
        System.out.println("queryCityByProvince.result=" + _queryCityByProvince__return);


        }
        {
        System.out.println("Invoking queryDeptByDistrict...");
        java.lang.String _queryDeptByDistrict_in0 = "";
        java.lang.String _queryDeptByDistrict_in1 = "";
        java.lang.String _queryDeptByDistrict_in2 = "";
        java.lang.String _queryDeptByDistrict_in3 = "";
        java.lang.String _queryDeptByDistrict_in4 = "";
        java.lang.String _queryDeptByDistrict_in5 = "";
        java.lang.String _queryDeptByDistrict__return = port.queryDeptByDistrict(_queryDeptByDistrict_in0, _queryDeptByDistrict_in1, _queryDeptByDistrict_in2, _queryDeptByDistrict_in3, _queryDeptByDistrict_in4, _queryDeptByDistrict_in5);
        System.out.println("queryDeptByDistrict.result=" + _queryDeptByDistrict__return);


        }
        {
        System.out.println("Invoking queryCountyByCity...");
        java.lang.String _queryCountyByCity_in0 = "";
        com.hoau.wechat.ws.wt.ArrayOfDistrictModel _queryCountyByCity__return = port.queryCountyByCity(_queryCountyByCity_in0);
        System.out.println("queryCountyByCity.result=" + _queryCountyByCity__return);


        }

        System.exit(0);
    }

}
