
package com.hoau.how.module.itf.server.ws.claim;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-09-16T21:23:57.185+08:00
 * Generated source version: 2.7.11
 * 
 */
 
public class ClaimsWBService_ClaimsWBServiceImplPort_Server{

    protected ClaimsWBService_ClaimsWBServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ClaimsWBServiceImpl();
        String address = "http://10.39.251.109/TDHY_CLAIMS/ws-services/claimsWBService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ClaimsWBService_ClaimsWBServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
