
package com.hoau.how.module.itf.server.ws.bank;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BaseAccountInfoServices", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BaseAccountInfoServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hoau.how.module.itf.server.ws.bank.AccountProvince>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountProvinceList", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.how.module.itf.server.ws.bank.GetAccountProvinceList")
    @ResponseWrapper(localName = "getAccountProvinceListResponse", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.how.module.itf.server.ws.bank.GetAccountProvinceListResponse")
    public List<AccountProvince> getAccountProvinceList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hoau.how.module.itf.server.ws.bank.AccountCity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountCityList", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.how.module.itf.server.ws.bank.GetAccountCityList")
    @ResponseWrapper(localName = "getAccountCityListResponse", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.how.module.itf.server.ws.bank.GetAccountCityListResponse")
    public List<AccountCity> getAccountCityList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hoau.how.module.itf.server.ws.bank.AccountBankInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountBankInfoList", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.how.module.itf.server.ws.bank.GetAccountBankInfoList")
    @ResponseWrapper(localName = "getAccountBankInfoListResponse", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.how.module.itf.server.ws.bank.GetAccountBankInfoListResponse")
    public List<AccountBankInfo> getAccountBankInfoList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
