--区县表
CREATE TABLE  t_bse_district  (
   ID  varchar(36) NOT NULL, 
   DISTRICT_CODE  varchar(30) DEFAULT NULL, 
   DISTRICT_NAME  varchar(100) DEFAULT NULL,
   DISTRICT_TYPE  varchar(20) DEFAULT NULL, 
   PINYIN  varchar(30) DEFAULT NULL, 
   VERSION_NO  bigint DEFAULT NULL,
   PARENT_DISTRICT_CODE  varchar(30) DEFAULT NULL,
   CREATE_TIME  datetime DEFAULT NULL,
   CREATE_USER_CODE  varchar(20) DEFAULT NULL,
   MODIFY_TIME  datetime DEFAULT NULL,
   MODIFY_USER_CODE  varchar(20) DEFAULT NULL 
);

--部门表
CREATE TABLE  t_bse_dept  (
   ID  varchar(36) NOT NULL,
   DEPT_CODE  varchar(50) DEFAULT NULL,
   DEPT_NAME  varchar(200) DEFAULT NULL,
   PARENT_DEPT_CODE  varchar(50) DEFAULT NULL,
   PARENT_DEPT_NAME  varchar(200) DEFAULT NULL,
   DEPT_NATURE  int DEFAULT NULL,
   LOGIST_CODE  varchar(100) DEFAULT NULL,
   MANAGER_CODE  varchar(20) DEFAULT NULL,
   MANAGER_NAME  varchar(100) DEFAULT NULL,
   PROVINCE  varchar(100) DEFAULT NULL,
   PROVINCE_CODE  varchar(20) DEFAULT NULL,
   CITY  varchar(100) DEFAULT NULL,
   CITY_CODE  varchar(20) DEFAULT NULL,
   COUNTY  varchar(100) DEFAULT NULL,
   COUNTY_CODE  varchar(20) DEFAULT NULL,
   AREA_CODE  varchar(20) DEFAULT NULL,
   PHONE  varchar(100) DEFAULT NULL,
   FAX  varchar(20) DEFAULT NULL,
   ADDRESS_DETAIL  varchar(200) DEFAULT NULL,
   LNG  float DEFAULT NULL,
   LAT  float DEFAULT NULL,
   IS_SPECIFIED_TIME  char(1) DEFAULT NULL,
   IS_SHIPMENT  char(1) DEFAULT NULL,
   IS_DELIVERY  char(1) DEFAULT NULL,
   IS_PICK_UP  char(1) DEFAULT NULL,
   ACTIVE  char(1) DEFAULT NULL,
   CREATE_TIME  datetime DEFAULT NULL,
   CREATE_USER_CODE  varchar(20) DEFAULT NULL,
   MODIFY_TIME  datetime DEFAULT NULL,
   MODIFY_USER_CODE  varchar(20) DEFAULT NULL,
   VERSION_NO  bigint DEFAULT NULL
) ;

