package com.hoau.wechat.ws.oms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-10-27T16:12:51.488+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "MobileService", 
                  wsdlLocation = "http://10.39.117.117:8081/HOAU_OL/services/MobileService?wsdl",
                  targetNamespace = "http://services.mobile.interfaces.sinotrans.com") 
public class MobileService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.mobile.interfaces.sinotrans.com", "MobileService");
    public final static QName MobileServiceHttpPort = new QName("http://services.mobile.interfaces.sinotrans.com", "MobileServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.39.117.117:8081/HOAU_OL/services/MobileService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MobileService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.39.117.117:8081/HOAU_OL/services/MobileService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MobileService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MobileService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns MobileServicePortType
     */
    @WebEndpoint(name = "MobileServiceHttpPort")
    public MobileServicePortType getMobileServiceHttpPort() {
        return super.getPort(MobileServiceHttpPort, MobileServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileServicePortType
     */
    @WebEndpoint(name = "MobileServiceHttpPort")
    public MobileServicePortType getMobileServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(MobileServiceHttpPort, MobileServicePortType.class, features);
    }

}
