
package com.hoau.how.module.itf.server.ws.dcpricetime;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-09-10T14:21:47.999+08:00
 * Generated source version: 3.0.2
 * 
 */
 
public class HowPriceAndTimeQueryServices_HowPriceAndTimeQueryServicesPort_Server{

    protected HowPriceAndTimeQueryServices_HowPriceAndTimeQueryServicesPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HowPriceAndTimeQueryServicesPortImpl();
        String address = "http://10.39.109.29:8080/services/HowPriceAndTimeQueryServices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new HowPriceAndTimeQueryServices_HowPriceAndTimeQueryServicesPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
