package com.hoau.how.module.obh.shared.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class ContactsEntity implements Serializable{
    /**
	 *
	 */
	private static final long serialVersionUID = 9158421743819365648L;
	List<UnpayMentEntity> unpayMentEntity;
	
	public List<UnpayMentEntity> getUnpayMentEntity() {
		return unpayMentEntity;
	}

	public void setUnpayMentEntity(List<UnpayMentEntity> unpayMentEntity) {
		this.unpayMentEntity = unpayMentEntity;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long ebsaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_contact
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_contact_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaContactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_is_default
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaIsDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_ebpv_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaEbpvName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_ebpl_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaEbplName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_ebco_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaEbcoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_company
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_contact_area_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaContactAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_esco_second_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaEscoSecondCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_esco_second_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaEscoSecondName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_ebcu_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long ebsaEbcuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_type
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_remark
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_shipper_address.ebsa_dept_district
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebsaDeptDistrict;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_id
     *
     * @return the value of eb_shipper_address.ebsa_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEbsaId() {
        return ebsaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_id
     *
     * @param ebsaId the value for eb_shipper_address.ebsa_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaId(Long ebsaId) {
        this.ebsaId = ebsaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_address
     *
     * @return the value of eb_shipper_address.ebsa_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaAddress() {
        return ebsaAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_address
     *
     * @param ebsaAddress the value for eb_shipper_address.ebsa_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaAddress(String ebsaAddress) {
        this.ebsaAddress = ebsaAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_contact
     *
     * @return the value of eb_shipper_address.ebsa_contact
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaContact() {
        return ebsaContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_contact
     *
     * @param ebsaContact the value for eb_shipper_address.ebsa_contact
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaContact(String ebsaContact) {
        this.ebsaContact = ebsaContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_contact_tel
     *
     * @return the value of eb_shipper_address.ebsa_contact_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaContactTel() {
        return ebsaContactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_contact_tel
     *
     * @param ebsaContactTel the value for eb_shipper_address.ebsa_contact_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaContactTel(String ebsaContactTel) {
        this.ebsaContactTel = ebsaContactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_is_default
     *
     * @return the value of eb_shipper_address.ebsa_is_default
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaIsDefault() {
        return ebsaIsDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_is_default
     *
     * @param ebsaIsDefault the value for eb_shipper_address.ebsa_is_default
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaIsDefault(String ebsaIsDefault) {
        this.ebsaIsDefault = ebsaIsDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.modify_time
     *
     * @return the value of eb_shipper_address.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.modify_time
     *
     * @param modifyTime the value for eb_shipper_address.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.modifier
     *
     * @return the value of eb_shipper_address.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.modifier
     *
     * @param modifier the value for eb_shipper_address.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.create_time
     *
     * @return the value of eb_shipper_address.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.create_time
     *
     * @param createTime the value for eb_shipper_address.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.creator
     *
     * @return the value of eb_shipper_address.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.creator
     *
     * @param creator the value for eb_shipper_address.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_ebpv_name
     *
     * @return the value of eb_shipper_address.ebsa_ebpv_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaEbpvName() {
        return ebsaEbpvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_ebpv_name
     *
     * @param ebsaEbpvName the value for eb_shipper_address.ebsa_ebpv_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaEbpvName(String ebsaEbpvName) {
        this.ebsaEbpvName = ebsaEbpvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_ebpl_name
     *
     * @return the value of eb_shipper_address.ebsa_ebpl_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaEbplName() {
        return ebsaEbplName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_ebpl_name
     *
     * @param ebsaEbplName the value for eb_shipper_address.ebsa_ebpl_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaEbplName(String ebsaEbplName) {
        this.ebsaEbplName = ebsaEbplName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_ebco_name
     *
     * @return the value of eb_shipper_address.ebsa_ebco_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaEbcoName() {
        return ebsaEbcoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_ebco_name
     *
     * @param ebsaEbcoName the value for eb_shipper_address.ebsa_ebco_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaEbcoName(String ebsaEbcoName) {
        this.ebsaEbcoName = ebsaEbcoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_company
     *
     * @return the value of eb_shipper_address.ebsa_company
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaCompany() {
        return ebsaCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_company
     *
     * @param ebsaCompany the value for eb_shipper_address.ebsa_company
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaCompany(String ebsaCompany) {
        this.ebsaCompany = ebsaCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_contact_area_code
     *
     * @return the value of eb_shipper_address.ebsa_contact_area_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaContactAreaCode() {
        return ebsaContactAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_contact_area_code
     *
     * @param ebsaContactAreaCode the value for eb_shipper_address.ebsa_contact_area_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaContactAreaCode(String ebsaContactAreaCode) {
        this.ebsaContactAreaCode = ebsaContactAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_esco_second_code
     *
     * @return the value of eb_shipper_address.ebsa_esco_second_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaEscoSecondCode() {
        return ebsaEscoSecondCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_esco_second_code
     *
     * @param ebsaEscoSecondCode the value for eb_shipper_address.ebsa_esco_second_code
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaEscoSecondCode(String ebsaEscoSecondCode) {
        this.ebsaEscoSecondCode = ebsaEscoSecondCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_esco_second_name
     *
     * @return the value of eb_shipper_address.ebsa_esco_second_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaEscoSecondName() {
        return ebsaEscoSecondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_esco_second_name
     *
     * @param ebsaEscoSecondName the value for eb_shipper_address.ebsa_esco_second_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaEscoSecondName(String ebsaEscoSecondName) {
        this.ebsaEscoSecondName = ebsaEscoSecondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_ebcu_id
     *
     * @return the value of eb_shipper_address.ebsa_ebcu_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEbsaEbcuId() {
        return ebsaEbcuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_ebcu_id
     *
     * @param ebsaEbcuId the value for eb_shipper_address.ebsa_ebcu_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaEbcuId(Long ebsaEbcuId) {
        this.ebsaEbcuId = ebsaEbcuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_type
     *
     * @return the value of eb_shipper_address.ebsa_type
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaType() {
        return ebsaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_type
     *
     * @param ebsaType the value for eb_shipper_address.ebsa_type
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaType(String ebsaType) {
        this.ebsaType = ebsaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_mobile
     *
     * @return the value of eb_shipper_address.ebsa_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaMobile() {
        return ebsaMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_mobile
     *
     * @param ebsaMobile the value for eb_shipper_address.ebsa_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaMobile(String ebsaMobile) {
        this.ebsaMobile = ebsaMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_remark
     *
     * @return the value of eb_shipper_address.ebsa_remark
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaRemark() {
        return ebsaRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_remark
     *
     * @param ebsaRemark the value for eb_shipper_address.ebsa_remark
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaRemark(String ebsaRemark) {
        this.ebsaRemark = ebsaRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_shipper_address.ebsa_dept_district
     *
     * @return the value of eb_shipper_address.ebsa_dept_district
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbsaDeptDistrict() {
        return ebsaDeptDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_shipper_address.ebsa_dept_district
     *
     * @param ebsaDeptDistrict the value for eb_shipper_address.ebsa_dept_district
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbsaDeptDistrict(String ebsaDeptDistrict) {
        this.ebsaDeptDistrict = ebsaDeptDistrict;
    }
}