package com.hoau.how.module.obh.shared.domain;

import java.io.Serializable;
import java.util.Date;

public class CustomerContactEntity implements Serializable{
    /**
	 *
	 */
	private static final long serialVersionUID = -8344163717895274843L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long ebccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_ebcu_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long ebccEbcuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_contact_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebccContactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebccMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebccTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_email
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebccEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_net_login
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebccNetLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_net_password
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebccNetPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebccAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_company
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebccCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_sex
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebccSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer_contact.ebcc_district
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebccDistrict;
    
    private String ebccRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_id
     *
     * @return the value of eb_customer_contact.ebcc_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEbccId() {
        return ebccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_id
     *
     * @param ebccId the value for eb_customer_contact.ebcc_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccId(Long ebccId) {
        this.ebccId = ebccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_ebcu_id
     *
     * @return the value of eb_customer_contact.ebcc_ebcu_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEbccEbcuId() {
        return ebccEbcuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_ebcu_id
     *
     * @param ebccEbcuId the value for eb_customer_contact.ebcc_ebcu_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccEbcuId(Long ebccEbcuId) {
        this.ebccEbcuId = ebccEbcuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_contact_name
     *
     * @return the value of eb_customer_contact.ebcc_contact_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbccContactName() {
        return ebccContactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_contact_name
     *
     * @param ebccContactName the value for eb_customer_contact.ebcc_contact_name
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccContactName(String ebccContactName) {
        this.ebccContactName = ebccContactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_mobile
     *
     * @return the value of eb_customer_contact.ebcc_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbccMobile() {
        return ebccMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_mobile
     *
     * @param ebccMobile the value for eb_customer_contact.ebcc_mobile
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccMobile(String ebccMobile) {
        this.ebccMobile = ebccMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_tel
     *
     * @return the value of eb_customer_contact.ebcc_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbccTel() {
        return ebccTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_tel
     *
     * @param ebccTel the value for eb_customer_contact.ebcc_tel
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccTel(String ebccTel) {
        this.ebccTel = ebccTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_email
     *
     * @return the value of eb_customer_contact.ebcc_email
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbccEmail() {
        return ebccEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_email
     *
     * @param ebccEmail the value for eb_customer_contact.ebcc_email
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccEmail(String ebccEmail) {
        this.ebccEmail = ebccEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.create_time
     *
     * @return the value of eb_customer_contact.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.create_time
     *
     * @param createTime the value for eb_customer_contact.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.creator
     *
     * @return the value of eb_customer_contact.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.creator
     *
     * @param creator the value for eb_customer_contact.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.modify_time
     *
     * @return the value of eb_customer_contact.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.modify_time
     *
     * @param modifyTime the value for eb_customer_contact.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.modifier
     *
     * @return the value of eb_customer_contact.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.modifier
     *
     * @param modifier the value for eb_customer_contact.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_net_login
     *
     * @return the value of eb_customer_contact.ebcc_net_login
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbccNetLogin() {
        return ebccNetLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_net_login
     *
     * @param ebccNetLogin the value for eb_customer_contact.ebcc_net_login
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccNetLogin(String ebccNetLogin) {
        this.ebccNetLogin = ebccNetLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_net_password
     *
     * @return the value of eb_customer_contact.ebcc_net_password
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbccNetPassword() {
        return ebccNetPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_net_password
     *
     * @param ebccNetPassword the value for eb_customer_contact.ebcc_net_password
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccNetPassword(String ebccNetPassword) {
        this.ebccNetPassword = ebccNetPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_address
     *
     * @return the value of eb_customer_contact.ebcc_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbccAddress() {
        return ebccAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_address
     *
     * @param ebccAddress the value for eb_customer_contact.ebcc_address
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccAddress(String ebccAddress) {
        this.ebccAddress = ebccAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_company
     *
     * @return the value of eb_customer_contact.ebcc_company
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbccCompany() {
        return ebccCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_company
     *
     * @param ebccCompany the value for eb_customer_contact.ebcc_company
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccCompany(String ebccCompany) {
        this.ebccCompany = ebccCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_sex
     *
     * @return the value of eb_customer_contact.ebcc_sex
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbccSex() {
        return ebccSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_sex
     *
     * @param ebccSex the value for eb_customer_contact.ebcc_sex
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccSex(String ebccSex) {
        this.ebccSex = ebccSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer_contact.ebcc_district
     *
     * @return the value of eb_customer_contact.ebcc_district
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbccDistrict() {
        return ebccDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer_contact.ebcc_district
     *
     * @param ebccDistrict the value for eb_customer_contact.ebcc_district
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbccDistrict(String ebccDistrict) {
        this.ebccDistrict = ebccDistrict;
    }

	public String getEbccRemark() {
		return ebccRemark;
	}

	public void setEbccRemark(String ebccRemark) {
		this.ebccRemark = ebccRemark;
	}
    
}