package com.hoau.wechat.ws.waybill;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-07-06T16:18:48.421+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "QuerySignInfoServices", 
                  wsdlLocation = "http://10.39.251.3:8080/hoaunew/services/QuerySignInfoServices?wsdl",
                  targetNamespace = "http://www.hoau.net/services/QuerySignInfoServices") 
public class QuerySignInfoServices_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.hoau.net/services/QuerySignInfoServices", "QuerySignInfoServices");
    public final static QName QuerySignInfoServicesPort = new QName("http://www.hoau.net/services/QuerySignInfoServices", "QuerySignInfoServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.39.251.3:8080/hoaunew/services/QuerySignInfoServices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QuerySignInfoServices_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.39.251.3:8080/hoaunew/services/QuerySignInfoServices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QuerySignInfoServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QuerySignInfoServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuerySignInfoServices_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns QuerySignInfoServices
     */
    @WebEndpoint(name = "QuerySignInfoServicesPort")
    public QuerySignInfoServices getQuerySignInfoServicesPort() {
        return super.getPort(QuerySignInfoServicesPort, QuerySignInfoServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuerySignInfoServices
     */
    @WebEndpoint(name = "QuerySignInfoServicesPort")
    public QuerySignInfoServices getQuerySignInfoServicesPort(WebServiceFeature... features) {
        return super.getPort(QuerySignInfoServicesPort, QuerySignInfoServices.class, features);
    }

}
