package com.hoau.mhow.invokews.server.ws.dcpricetime;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-12-18T11:50:38.813+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.hoau.net/services/HowPriceAndTimeQueryServices", name = "HowPriceAndTimeQueryServices")
@XmlSeeAlso({ObjectFactory.class})
public interface HowPriceAndTimeQueryServices {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPriceAndTime", targetNamespace = "http://www.hoau.net/services/HowPriceAndTimeQueryServices", className = "com.hoau.mhow.invokews.server.ws.dcpricetime.QueryPriceAndTime")
    @WebMethod
    @ResponseWrapper(localName = "queryPriceAndTimeResponse", targetNamespace = "http://www.hoau.net/services/HowPriceAndTimeQueryServices", className = "com.hoau.mhow.invokews.server.ws.dcpricetime.QueryPriceAndTimeResponse")
    public java.util.List<com.hoau.mhow.invokews.server.ws.dcpricetime.PriceQueryResult> queryPriceAndTime(
        @WebParam(name = "arg0", targetNamespace = "")
        com.hoau.mhow.invokews.server.ws.dcpricetime.PriceQueryVo arg0
    );
}
