
package com.hoau.mhow.invokews.server.ws.omsorder;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-12-18T11:50:06.736+08:00
 * Generated source version: 2.7.11
 * 
 */
 
public class CustomerServicePortType_CustomerServiceHttpPort_Server{

    protected CustomerServicePortType_CustomerServiceHttpPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CustomerServicePortTypeImpl();
        String address = "http://testoms.hoau.net/services/CustomerService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CustomerServicePortType_CustomerServiceHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
