package com.hoau.how.module.itf.server.ws.waybilldetail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-13T11:22:08.515+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://www.szzc.com.cn/services/WptServices", name = "WptServices")
@XmlSeeAlso({ObjectFactory.class})
public interface WptServices {

	@WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWptYdInfo", targetNamespace = "http://www.szzc.com.cn/services/WptServices", className = "com.hoau.how.module.itf.server.ws.waybilldetail.GetWptYdInfo")
    @WebMethod
    @ResponseWrapper(localName = "getWptYdInfoResponse", targetNamespace = "http://www.szzc.com.cn/services/WptServices", className = "com.hoau.how.module.itf.server.ws.waybilldetail.GetWptYdInfoResponse")
    public java.util.List<com.hoau.how.module.itf.server.ws.waybilldetail.WptYdInfo> getWptYdInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "queryOneWaybill", targetNamespace = "http://www.szzc.com.cn/services/WptServices", className = "com.hoau.how.module.itf.server.ws.waybilldetail.QueryOneWaybill")
    @ResponseWrapper(localName = "queryOneWaybillResponse", targetNamespace = "http://www.szzc.com.cn/services/WptServices", className = "com.hoau.how.module.itf.server.ws.waybilldetail.QueryOneWaybillResponse")
    @WebResult(name = "return", targetNamespace = "")
    public WaybillInfo queryOneWaybill(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
