
package com.hoau.how.module.itf.server.ws.goodstrace;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-06-16T18:04:49.037+08:00
 * Generated source version: 3.0.1
 * 
 */
 
public class TNTService_TNTServicePort_Server{

    protected TNTService_TNTServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new TNTServicePortImpl();
        String address = "http://10.39.109.20:9080/tnt/services/tntServices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new TNTService_TNTServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
