
package com.hoau.wechat.ws.waybill;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-07-06T16:18:48.380+08:00
 * Generated source version: 3.0.2
 * 
 */
public final class QuerySignInfoServices_QuerySignInfoServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.hoau.net/services/QuerySignInfoServices", "QuerySignInfoServices");

    private QuerySignInfoServices_QuerySignInfoServicesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QuerySignInfoServices_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QuerySignInfoServices_Service ss = new QuerySignInfoServices_Service(wsdlURL, SERVICE_NAME);
        QuerySignInfoServices port = ss.getQuerySignInfoServicesPort();  
        
        {
        System.out.println("Invoking queryWaybill...");
        java.lang.String _queryWaybill_arg0 = "";
        java.lang.String _queryWaybill_arg1 = "";
        com.hoau.wechat.ws.waybill.WaybillInfo _queryWaybill__return = port.queryWaybill(_queryWaybill_arg0, _queryWaybill_arg1);
        System.out.println("queryWaybill.result=" + _queryWaybill__return);


        }
        {
        System.out.println("Invoking querySignInfoServices...");
        java.lang.String _querySignInfoServices_arg0 = "";
        com.hoau.wechat.ws.waybill.SignInfoEntity _querySignInfoServices__return = port.querySignInfoServices(_querySignInfoServices_arg0);
        System.out.println("querySignInfoServices.result=" + _querySignInfoServices__return);


        }

        System.exit(0);
    }

}
