package com.hoau.mhow.invokews.server.ws.goodstrace;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-12-18T11:50:53.673+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "TNTServiceService", 
                  wsdlLocation = "http://10.39.109.20:9080/tnt/services/tntServices?wsdl",
                  targetNamespace = "http://ws.datamanagement.barcode.hoau.com/") 
public class TNTServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.datamanagement.barcode.hoau.com/", "TNTServiceService");
    public final static QName TNTServicePort = new QName("http://ws.datamanagement.barcode.hoau.com/", "TNTServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.39.109.20:9080/tnt/services/tntServices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TNTServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.39.109.20:9080/tnt/services/tntServices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TNTServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TNTServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TNTServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TNTService
     */
    @WebEndpoint(name = "TNTServicePort")
    public TNTService getTNTServicePort() {
        return super.getPort(TNTServicePort, TNTService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TNTService
     */
    @WebEndpoint(name = "TNTServicePort")
    public TNTService getTNTServicePort(WebServiceFeature... features) {
        return super.getPort(TNTServicePort, TNTService.class, features);
    }

}
