package com.hoau.wechat.ws.waybill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-07-06T16:18:48.412+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://www.hoau.net/services/QuerySignInfoServices", name = "QuerySignInfoServices")
@XmlSeeAlso({ObjectFactory.class})
public interface QuerySignInfoServices {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://www.hoau.net/services/QuerySignInfoServices/QuerySignInfoServices/queryWaybillRequest", output = "http://www.hoau.net/services/QuerySignInfoServices/QuerySignInfoServices/queryWaybillResponse")
    @RequestWrapper(localName = "queryWaybill", targetNamespace = "http://www.hoau.net/services/QuerySignInfoServices", className = "com.hoau.wechat.ws.waybill.QueryWaybill")
    @WebMethod
    @ResponseWrapper(localName = "queryWaybillResponse", targetNamespace = "http://www.hoau.net/services/QuerySignInfoServices", className = "com.hoau.wechat.ws.waybill.QueryWaybillResponse")
    public com.hoau.wechat.ws.waybill.WaybillInfo queryWaybill(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://www.hoau.net/services/QuerySignInfoServices/QuerySignInfoServices/querySignInfoServicesRequest", output = "http://www.hoau.net/services/QuerySignInfoServices/QuerySignInfoServices/querySignInfoServicesResponse")
    @RequestWrapper(localName = "querySignInfoServices", targetNamespace = "http://www.hoau.net/services/QuerySignInfoServices", className = "com.hoau.wechat.ws.waybill.QuerySignInfoServices_Type")
    @WebMethod
    @ResponseWrapper(localName = "querySignInfoServicesResponse", targetNamespace = "http://www.hoau.net/services/QuerySignInfoServices", className = "com.hoau.wechat.ws.waybill.QuerySignInfoServicesResponse")
    public com.hoau.wechat.ws.waybill.SignInfoEntity querySignInfoServices(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
