package com.hoau.mhow.invokews.server.ws.goodstrace;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-12-18T11:50:53.661+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://ws.datamanagement.barcode.hoau.com/", name = "TNTService")
@XmlSeeAlso({ObjectFactory.class})
public interface TNTService {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.datamanagement.barcode.hoau.com/TNTService/getWebYdTraceByLevelRequest", output = "http://ws.datamanagement.barcode.hoau.com/TNTService/getWebYdTraceByLevelResponse")
    @RequestWrapper(localName = "getWebYdTraceByLevel", targetNamespace = "http://ws.datamanagement.barcode.hoau.com/", className = "com.hoau.mhow.invokews.server.ws.goodstrace.GetWebYdTraceByLevel")
    @WebMethod
    @ResponseWrapper(localName = "getWebYdTraceByLevelResponse", targetNamespace = "http://ws.datamanagement.barcode.hoau.com/", className = "com.hoau.mhow.invokews.server.ws.goodstrace.GetWebYdTraceByLevelResponse")
    public com.hoau.mhow.invokews.server.ws.goodstrace.YdTraceResponse getWebYdTraceByLevel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.datamanagement.barcode.hoau.com/TNTService/getGPSStatusRequest", output = "http://ws.datamanagement.barcode.hoau.com/TNTService/getGPSStatusResponse")
    @RequestWrapper(localName = "getGPSStatus", targetNamespace = "http://ws.datamanagement.barcode.hoau.com/", className = "com.hoau.mhow.invokews.server.ws.goodstrace.GetGPSStatus")
    @WebMethod
    @ResponseWrapper(localName = "getGPSStatusResponse", targetNamespace = "http://ws.datamanagement.barcode.hoau.com/", className = "com.hoau.mhow.invokews.server.ws.goodstrace.GetGPSStatusResponse")
    public com.hoau.mhow.invokews.server.ws.goodstrace.GpsStatusResponse getGPSStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.datamanagement.barcode.hoau.com/TNTService/getYdTraceRequest", output = "http://ws.datamanagement.barcode.hoau.com/TNTService/getYdTraceResponse")
    @RequestWrapper(localName = "getYdTrace", targetNamespace = "http://ws.datamanagement.barcode.hoau.com/", className = "com.hoau.mhow.invokews.server.ws.goodstrace.GetYdTrace")
    @WebMethod
    @ResponseWrapper(localName = "getYdTraceResponse", targetNamespace = "http://ws.datamanagement.barcode.hoau.com/", className = "com.hoau.mhow.invokews.server.ws.goodstrace.GetYdTraceResponse")
    public com.hoau.mhow.invokews.server.ws.goodstrace.YdTraceResponse getYdTrace(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.datamanagement.barcode.hoau.com/TNTService/getWebYdTraceRequest", output = "http://ws.datamanagement.barcode.hoau.com/TNTService/getWebYdTraceResponse")
    @RequestWrapper(localName = "getWebYdTrace", targetNamespace = "http://ws.datamanagement.barcode.hoau.com/", className = "com.hoau.mhow.invokews.server.ws.goodstrace.GetWebYdTrace")
    @WebMethod
    @ResponseWrapper(localName = "getWebYdTraceResponse", targetNamespace = "http://ws.datamanagement.barcode.hoau.com/", className = "com.hoau.mhow.invokews.server.ws.goodstrace.GetWebYdTraceResponse")
    public com.hoau.mhow.invokews.server.ws.goodstrace.YdTraceResponse getWebYdTrace(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.datamanagement.barcode.hoau.com/TNTService/getWebDkhYdTraceRequest", output = "http://ws.datamanagement.barcode.hoau.com/TNTService/getWebDkhYdTraceResponse")
    @RequestWrapper(localName = "getWebDkhYdTrace", targetNamespace = "http://ws.datamanagement.barcode.hoau.com/", className = "com.hoau.mhow.invokews.server.ws.goodstrace.GetWebDkhYdTrace")
    @WebMethod
    @ResponseWrapper(localName = "getWebDkhYdTraceResponse", targetNamespace = "http://ws.datamanagement.barcode.hoau.com/", className = "com.hoau.mhow.invokews.server.ws.goodstrace.GetWebDkhYdTraceResponse")
    public com.hoau.mhow.invokews.server.ws.goodstrace.DkhYdTraceResponse getWebDkhYdTrace(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.List<java.lang.String> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5
    );
}
