package com.hoau.mhow.module.bse.api.shared.domain;

import java.io.Serializable;
import java.util.Date;

public class CustomerEntity implements Serializable{
    /**
	 *
	 */
	private static final long serialVersionUID = -3602794181789034302L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer.ebcu_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Long ebcuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer.ebcu_customer_no
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebcuCustomerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer.ebcu_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String ebcuNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_customer.ebcu_invited_status
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    private Short ebcuInvitedStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer.ebcu_id
     *
     * @return the value of eb_customer.ebcu_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Long getEbcuId() {
        return ebcuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer.ebcu_id
     *
     * @param ebcuId the value for eb_customer.ebcu_id
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbcuId(Long ebcuId) {
        this.ebcuId = ebcuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer.ebcu_customer_no
     *
     * @return the value of eb_customer.ebcu_customer_no
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbcuCustomerNo() {
        return ebcuCustomerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer.ebcu_customer_no
     *
     * @param ebcuCustomerNo the value for eb_customer.ebcu_customer_no
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbcuCustomerNo(String ebcuCustomerNo) {
        this.ebcuCustomerNo = ebcuCustomerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer.ebcu_name_cn
     *
     * @return the value of eb_customer.ebcu_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getEbcuNameCn() {
        return ebcuNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer.ebcu_name_cn
     *
     * @param ebcuNameCn the value for eb_customer.ebcu_name_cn
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbcuNameCn(String ebcuNameCn) {
        this.ebcuNameCn = ebcuNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer.create_time
     *
     * @return the value of eb_customer.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer.create_time
     *
     * @param createTime the value for eb_customer.create_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer.modify_time
     *
     * @return the value of eb_customer.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer.modify_time
     *
     * @param modifyTime the value for eb_customer.modify_time
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer.modifier
     *
     * @return the value of eb_customer.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer.modifier
     *
     * @param modifier the value for eb_customer.modifier
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer.creator
     *
     * @return the value of eb_customer.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer.creator
     *
     * @param creator the value for eb_customer.creator
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_customer.ebcu_invited_status
     *
     * @return the value of eb_customer.ebcu_invited_status
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public Short getEbcuInvitedStatus() {
        return ebcuInvitedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_customer.ebcu_invited_status
     *
     * @param ebcuInvitedStatus the value for eb_customer.ebcu_invited_status
     *
     * @mbggenerated Wed Oct 14 11:34:50 CST 2015
     */
    public void setEbcuInvitedStatus(Short ebcuInvitedStatus) {
        this.ebcuInvitedStatus = ebcuInvitedStatus;
    }
}