package com.hoau.mhow.invokews.server.ws.omsorder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-12-18T11:50:06.740+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "CustomerService", 
                  wsdlLocation = "http://testoms.hoau.net/services/CustomerService?wsdl",
                  targetNamespace = "http://services.customer.interfaces.sinotrans.com") 
public class CustomerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.customer.interfaces.sinotrans.com", "CustomerService");
    public final static QName CustomerServiceHttpPort = new QName("http://services.customer.interfaces.sinotrans.com", "CustomerServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://testoms.hoau.net/services/CustomerService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://testoms.hoau.net/services/CustomerService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CustomerServicePortType
     */
    @WebEndpoint(name = "CustomerServiceHttpPort")
    public CustomerServicePortType getCustomerServiceHttpPort() {
        return super.getPort(CustomerServiceHttpPort, CustomerServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerServicePortType
     */
    @WebEndpoint(name = "CustomerServiceHttpPort")
    public CustomerServicePortType getCustomerServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(CustomerServiceHttpPort, CustomerServicePortType.class, features);
    }

}
