package com.hoau.how.module.itf.server.ws.omsorder;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-07-30T16:59:51.812+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "CustomerService", 
                  wsdlLocation = "http://oms.hoau.net/services/CustomerService?wsdl",
                  targetNamespace = "http://services.customer.interfaces.sinotrans.com") 
public class CustomerService extends Service {

    public final static QName SERVICE = new QName("http://services.customer.interfaces.sinotrans.com", "CustomerService");
    public final static QName CustomerServiceHttpPort = new QName("http://services.customer.interfaces.sinotrans.com", "CustomerServiceHttpPort");
    
    public CustomerService(URL wsdlLocation) {
    	super(wsdlLocation, SERVICE);
    }

    /**
     *
     * @return
     *     returns CustomerServicePortType
     */
    @WebEndpoint(name = "CustomerServiceHttpPort")
    public CustomerServicePortType getCustomerServiceHttpPort() {
        return super.getPort(CustomerServiceHttpPort, CustomerServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerServicePortType
     */
    @WebEndpoint(name = "CustomerServiceHttpPort")
    public CustomerServicePortType getCustomerServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(CustomerServiceHttpPort, CustomerServicePortType.class, features);
    }

}
