
package com.hoau.mhow.invokews.server.ws.goodstrace;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-12-18T11:50:53.622+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class TNTService_TNTServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.datamanagement.barcode.hoau.com/", "TNTServiceService");

    private TNTService_TNTServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TNTServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TNTServiceService ss = new TNTServiceService(wsdlURL, SERVICE_NAME);
        TNTService port = ss.getTNTServicePort();  
        
        {
        System.out.println("Invoking getWebYdTraceByLevel...");
        java.util.List<java.lang.String> _getWebYdTraceByLevel_arg0 = null;
        java.lang.String _getWebYdTraceByLevel_arg1 = "";
        java.lang.String _getWebYdTraceByLevel_arg2 = "";
        java.lang.String _getWebYdTraceByLevel_arg3 = "";
        com.hoau.mhow.invokews.server.ws.goodstrace.YdTraceResponse _getWebYdTraceByLevel__return = port.getWebYdTraceByLevel(_getWebYdTraceByLevel_arg0, _getWebYdTraceByLevel_arg1, _getWebYdTraceByLevel_arg2, _getWebYdTraceByLevel_arg3);
        System.out.println("getWebYdTraceByLevel.result=" + _getWebYdTraceByLevel__return);


        }
        {
        System.out.println("Invoking getGPSStatus...");
        java.lang.String _getGPSStatus_arg0 = "";
        com.hoau.mhow.invokews.server.ws.goodstrace.GpsStatusResponse _getGPSStatus__return = port.getGPSStatus(_getGPSStatus_arg0);
        System.out.println("getGPSStatus.result=" + _getGPSStatus__return);


        }
        {
        System.out.println("Invoking getYdTrace...");
        java.util.List<java.lang.String> _getYdTrace_arg0 = null;
        com.hoau.mhow.invokews.server.ws.goodstrace.YdTraceResponse _getYdTrace__return = port.getYdTrace(_getYdTrace_arg0);
        System.out.println("getYdTrace.result=" + _getYdTrace__return);


        }
        {
        System.out.println("Invoking getWebYdTrace...");
        java.util.List<java.lang.String> _getWebYdTrace_arg0 = null;
        java.lang.String _getWebYdTrace_arg1 = "";
        java.lang.String _getWebYdTrace_arg2 = "";
        java.lang.String _getWebYdTrace_arg3 = "";
        com.hoau.mhow.invokews.server.ws.goodstrace.YdTraceResponse _getWebYdTrace__return = port.getWebYdTrace(_getWebYdTrace_arg0, _getWebYdTrace_arg1, _getWebYdTrace_arg2, _getWebYdTrace_arg3);
        System.out.println("getWebYdTrace.result=" + _getWebYdTrace__return);


        }
        {
        System.out.println("Invoking getWebDkhYdTrace...");
        java.lang.String _getWebDkhYdTrace_arg0 = "";
        java.util.List<java.lang.String> _getWebDkhYdTrace_arg1 = null;
        java.util.List<java.lang.String> _getWebDkhYdTrace_arg2 = null;
        java.lang.String _getWebDkhYdTrace_arg3 = "";
        java.lang.String _getWebDkhYdTrace_arg4 = "";
        int _getWebDkhYdTrace_arg5 = 0;
        com.hoau.mhow.invokews.server.ws.goodstrace.DkhYdTraceResponse _getWebDkhYdTrace__return = port.getWebDkhYdTrace(_getWebDkhYdTrace_arg0, _getWebDkhYdTrace_arg1, _getWebDkhYdTrace_arg2, _getWebDkhYdTrace_arg3, _getWebDkhYdTrace_arg4, _getWebDkhYdTrace_arg5);
        System.out.println("getWebDkhYdTrace.result=" + _getWebDkhYdTrace__return);


        }

        System.exit(0);
    }

}
