
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.how.module.itf.server.ws.claim;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-09-16T21:23:57.159+08:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "ClaimsWBServiceImplService",
                      portName = "ClaimsWBServiceImplPort",
                      targetNamespace = "http://hoauweb.ws.erry.com/",
                      wsdlLocation = "http://10.39.251.109/TDHY_CLAIMS/ws-services/claimsWBService?wsdl",
                      endpointInterface = "com.hoau.how.module.itf.server.ws.claim.ClaimsWBService")
                      
public class ClaimsWBServiceImpl implements ClaimsWBService {

    private static final Logger LOG = Logger.getLogger(ClaimsWBServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.claim.ClaimsWBService#findByClaimsPic(java.lang.String  billNo ,)java.lang.String  claimsNo )*
     */
    public com.hoau.how.module.itf.server.ws.claim.ResponseQueryFiles findByClaimsPic(java.lang.String billNo,java.lang.String claimsNo) { 
        LOG.info("Executing operation findByClaimsPic");
        System.out.println(billNo);
        System.out.println(claimsNo);
        try {
            com.hoau.how.module.itf.server.ws.claim.ResponseQueryFiles _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.claim.ClaimsWBService#confirmClaimsAmount(java.lang.String  claimsNo )*
     */
    public com.hoau.how.module.itf.server.ws.claim.ResponseClaimsObject confirmClaimsAmount(java.lang.String claimsNo) { 
        LOG.info("Executing operation confirmClaimsAmount");
        System.out.println(claimsNo);
        try {
            com.hoau.how.module.itf.server.ws.claim.ResponseClaimsObject _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.claim.ClaimsWBService#getClaims(java.lang.String  userID )*
     */
    public com.hoau.how.module.itf.server.ws.claim.ResponseQueryClaims getClaims(java.lang.String userID) { 
        LOG.info("Executing operation getClaims");
        System.out.println(userID);
        try {
            com.hoau.how.module.itf.server.ws.claim.ResponseQueryClaims _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.claim.ClaimsWBService#uploadClaims(com.hoau.how.module.itf.server.ws.claim.ClaimsInfo  claimsInfo )*
     */
    public com.hoau.how.module.itf.server.ws.claim.ResponseClaimsObject uploadClaims(com.hoau.how.module.itf.server.ws.claim.ClaimsInfo claimsInfo) { 
        LOG.info("Executing operation uploadClaims");
        System.out.println(claimsInfo);
        try {
            com.hoau.how.module.itf.server.ws.claim.ResponseClaimsObject _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.claim.ClaimsWBService#findClaimsPlace(java.lang.String  billNo ,)java.lang.String  billTel )*
     */
    public java.util.List<com.hoau.how.module.itf.server.ws.claim.QueryCorpResult> findClaimsPlace(java.lang.String billNo,java.lang.String billTel) { 
        LOG.info("Executing operation findClaimsPlace");
        System.out.println(billNo);
        System.out.println(billTel);
        try {
            java.util.List<com.hoau.how.module.itf.server.ws.claim.QueryCorpResult> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    @Override
	public ResponseClaimsObject refuseClaimsAmount(String billNo) {
		 LOG.info("Executing operation refuseClaimsAmount");
	        System.out.println(billNo);
	        try {
	            com.hoau.how.module.itf.server.ws.claim.ResponseClaimsObject _return = null;
	            return _return;
	        } catch (java.lang.Exception ex) {
	            ex.printStackTrace();
	            throw new RuntimeException(ex);
	        }
	}

	/* (non-Javadoc)
	 * @see com.hoau.how.module.itf.server.ws.claim.ClaimsWBService#findClaimsDetail(java.lang.String, java.lang.String)
	 */
	@Override
	public ResponseQueryDetail findClaimsDetail(String arg0, String arg1) {
		return null;
	}

}
