
package com.hoau.how.module.itf.server.ws.claim;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-09-16T21:23:57.137+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class ClaimsWBService_ClaimsWBServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://hoauweb.ws.erry.com/", "ClaimsWBServiceImplService");

    private ClaimsWBService_ClaimsWBServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClaimsWBServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ClaimsWBServiceImplService ss = new ClaimsWBServiceImplService(wsdlURL, SERVICE_NAME);
        ClaimsWBService port = ss.getClaimsWBServiceImplPort();  
        
//        {
//        System.out.println("Invoking findByClaimsPic...");
//        java.lang.String _findByClaimsPic_billNo = "";
//        com.hoau.how.module.itf.server.ws.claim.ResponseClaimsObject _findByClaimsPic__return = port.refuseClaimsAmount(_findByClaimsPic_billNo);
//        System.out.println("findByClaimsPic.result=" + _findByClaimsPic__return.getErrorMessage());
//
//
//        }
//        {
//        	System.out.println("Invoking findByClaimsPic...");
//        	java.lang.String _findByClaimsPic_billNo = "";
//        	java.lang.String _findByClaimsPic_claimsNo = "";
//        	com.hoau.how.module.itf.server.ws.claim.ResponseQueryFiles _findByClaimsPic__return = port.findByClaimsPic(_findByClaimsPic_billNo, _findByClaimsPic_claimsNo);
//        	System.out.println("findByClaimsPic.result=" + _findByClaimsPic__return);
//        	
//        	
//        }
//        {
//        System.out.println("Invoking confirmClaimsAmount...");
//        java.lang.String _confirmClaimsAmount_claimsNo = "";
//        com.hoau.how.module.itf.server.ws.claim.ResponseClaimsObject _confirmClaimsAmount__return = port.confirmClaimsAmount(_confirmClaimsAmount_claimsNo);
//        System.out.println("confirmClaimsAmount.result=" + _confirmClaimsAmount__return);
//
//
//        }
        {
        System.out.println("Invoking getClaims...");
        java.lang.String _getClaims_userID = "35379605";
        com.hoau.how.module.itf.server.ws.claim.ResponseQueryClaims _getClaims__return = port.getClaims(_getClaims_userID);
        System.out.println("getClaims.result=" + _getClaims__return);


        }
//        {
//        System.out.println("Invoking uploadClaims...");
//        com.hoau.how.module.itf.server.ws.claim.ClaimsInfo _uploadClaims_claimsInfo = null;
//        com.hoau.how.module.itf.server.ws.claim.ResponseClaimsObject _uploadClaims__return = port.uploadClaims(_uploadClaims_claimsInfo);
//        System.out.println("uploadClaims.result=" + _uploadClaims__return);
//
//
//        }
//        {
//        System.out.println("Invoking findClaimsPlace...");
//        java.lang.String _findClaimsPlace_billNo = "";
//        java.lang.String _findClaimsPlace_billTel = "";
//        java.util.List<com.hoau.how.module.itf.server.ws.claim.QueryCorpResult> _findClaimsPlace__return = port.findClaimsPlace(_findClaimsPlace_billNo, _findClaimsPlace_billTel);
//        System.out.println("findClaimsPlace.result=" + _findClaimsPlace__return);
//
//
//        }

        System.exit(0);
    }

}
