
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.how.module.itf.server.ws.goodstrace;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-06-16T18:04:49.015+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "TNTServiceService",
                      portName = "TNTServicePort",
                      targetNamespace = "http://ws.datamanagement.barcode.hoau.com/",
                      wsdlLocation = "http://10.39.109.20:9080/tnt/services/tntServices?wsdl",
                      endpointInterface = "com.hoau.how.module.itf.server.ws.goodstrace.TNTService")
                      
public class TNTServicePortImpl implements TNTService {

    private static final Logger LOG = Logger.getLogger(TNTServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.goodstrace.TNTService#getWebYdTraceByLevel(java.util.List<java.lang.String>  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 )*
     */
    public com.hoau.how.module.itf.server.ws.goodstrace.YdTraceResponse getWebYdTraceByLevel(java.util.List<java.lang.String> arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3) { 
        LOG.info("Executing operation getWebYdTraceByLevel");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            com.hoau.how.module.itf.server.ws.goodstrace.YdTraceResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.goodstrace.TNTService#getGPSStatus(java.lang.String  arg0 )*
     */
    public com.hoau.how.module.itf.server.ws.goodstrace.GpsStatusResponse getGPSStatus(java.lang.String arg0) { 
        LOG.info("Executing operation getGPSStatus");
        System.out.println(arg0);
        try {
            com.hoau.how.module.itf.server.ws.goodstrace.GpsStatusResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.goodstrace.TNTService#getYdTrace(java.util.List<java.lang.String>  arg0 )*
     */
    public com.hoau.how.module.itf.server.ws.goodstrace.YdTraceResponse getYdTrace(java.util.List<java.lang.String> arg0) { 
        LOG.info("Executing operation getYdTrace");
        System.out.println(arg0);
        try {
            com.hoau.how.module.itf.server.ws.goodstrace.YdTraceResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.goodstrace.TNTService#getWebDkhYdTrace(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 ,)java.util.List<java.lang.String>  arg2 ,)java.lang.String  arg3 ,)java.lang.String  arg4 ,)int  arg5 )*
     */
    public com.hoau.how.module.itf.server.ws.goodstrace.DkhYdTraceResponse getWebDkhYdTrace(java.lang.String arg0,java.util.List<java.lang.String> arg1,java.util.List<java.lang.String> arg2,java.lang.String arg3,java.lang.String arg4,int arg5) { 
        LOG.info("Executing operation getWebDkhYdTrace");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        try {
            com.hoau.how.module.itf.server.ws.goodstrace.DkhYdTraceResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.goodstrace.TNTService#getWebYdTrace(java.util.List<java.lang.String>  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 )*
     */
    public com.hoau.how.module.itf.server.ws.goodstrace.YdTraceResponse getWebYdTrace(java.util.List<java.lang.String> arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3) { 
        LOG.info("Executing operation getWebYdTrace");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            com.hoau.how.module.itf.server.ws.goodstrace.YdTraceResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
