
package com.hoau.mhow.invokews.server.ws.omsorder;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-12-18T11:50:06.685+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class CustomerServicePortType_CustomerServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.customer.interfaces.sinotrans.com", "CustomerService");

    private CustomerServicePortType_CustomerServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CustomerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CustomerService ss = new CustomerService(wsdlURL, SERVICE_NAME);
        CustomerServicePortType port = ss.getCustomerServiceHttpPort();  
        
        {
        System.out.println("Invoking modifyOrder...");
        com.hoau.mhow.invokews.server.ws.omsorder.CustOrderReqModel _modifyOrder_in0 = null;
        com.hoau.mhow.invokews.server.ws.omsorder.CustOrderResModel _modifyOrder__return = port.modifyOrder(_modifyOrder_in0);
        System.out.println("modifyOrder.result=" + _modifyOrder__return);


        }
        {
        System.out.println("Invoking cancelOrder...");
        com.hoau.mhow.invokews.server.ws.omsorder.CancelOrderReqModel _cancelOrder_in0 = null;
        com.hoau.mhow.invokews.server.ws.omsorder.CancelOrderResModel _cancelOrder__return = port.cancelOrder(_cancelOrder_in0);
        System.out.println("cancelOrder.result=" + _cancelOrder__return);


        }
        {
        System.out.println("Invoking cutomerOrder...");
        com.hoau.mhow.invokews.server.ws.omsorder.CustOrderReqModel _cutomerOrder_in0 = null;
        com.hoau.mhow.invokews.server.ws.omsorder.CustOrderResModel _cutomerOrder__return = port.cutomerOrder(_cutomerOrder_in0);
        System.out.println("cutomerOrder.result=" + _cutomerOrder__return);


        }
        {
        System.out.println("Invoking saveNetOrder...");
        com.hoau.mhow.invokews.server.ws.omsorder.EiNetOrderReqModel _saveNetOrder_in0 = null;
        com.hoau.mhow.invokews.server.ws.omsorder.EiNetOrderReqModel _saveNetOrder__return = port.saveNetOrder(_saveNetOrder_in0);
        System.out.println("saveNetOrder.result=" + _saveNetOrder__return);


        }
        {
        System.out.println("Invoking updateNetOrder...");
        com.hoau.mhow.invokews.server.ws.omsorder.EiNetOrderReqModel _updateNetOrder_in0 = null;
        com.hoau.mhow.invokews.server.ws.omsorder.EiNetOrderReq _updateNetOrder__return = port.updateNetOrder(_updateNetOrder_in0);
        System.out.println("updateNetOrder.result=" + _updateNetOrder__return);


        }
        {
        System.out.println("Invoking trackOrder...");
        com.hoau.mhow.invokews.server.ws.omsorder.TrackOrderReqModel _trackOrder_in0 = null;
        com.hoau.mhow.invokews.server.ws.omsorder.TrackOrderResModel _trackOrder__return = port.trackOrder(_trackOrder_in0);
        System.out.println("trackOrder.result=" + _trackOrder__return);


        }
        {
        System.out.println("Invoking queryOrder...");
        com.hoau.mhow.invokews.server.ws.omsorder.QueryOrderReqModel _queryOrder_in0 = null;
        com.hoau.mhow.invokews.server.ws.omsorder.QueryOrderResModel _queryOrder__return = port.queryOrder(_queryOrder_in0);
        System.out.println("queryOrder.result=" + _queryOrder__return);


        }

        System.exit(0);
    }

}
