package com.hoau.how.module.itf.server.ws.claim;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-14T11:28:19.829+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://hoauweb.ws.erry.com/", name = "ClaimsWBService")
@XmlSeeAlso({ObjectFactory.class})
public interface ClaimsWBService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findByClaimsPic", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.FindByClaimsPic")
    @WebMethod
    @ResponseWrapper(localName = "findByClaimsPicResponse", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.FindByClaimsPicResponse")
    public com.hoau.how.module.itf.server.ws.claim.ResponseQueryFiles findByClaimsPic(
        @WebParam(name = "billNo", targetNamespace = "")
        java.lang.String billNo,
        @WebParam(name = "claimsNo", targetNamespace = "")
        java.lang.String claimsNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "confirmClaimsAmount", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.ConfirmClaimsAmount")
    @WebMethod
    @ResponseWrapper(localName = "confirmClaimsAmountResponse", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.ConfirmClaimsAmountResponse")
    public com.hoau.how.module.itf.server.ws.claim.ResponseClaimsObject confirmClaimsAmount(
        @WebParam(name = "claimsNo", targetNamespace = "")
        java.lang.String claimsNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "refuseClaimsAmount", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.RefuseClaimsAmount")
    @WebMethod
    @ResponseWrapper(localName = "refuseClaimsAmountResponse", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.RefuseClaimsAmountResponse")
    public com.hoau.how.module.itf.server.ws.claim.ResponseClaimsObject refuseClaimsAmount(
        @WebParam(name = "billNo", targetNamespace = "")
        java.lang.String billNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getClaims", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.GetClaims")
    @WebMethod
    @ResponseWrapper(localName = "getClaimsResponse", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.GetClaimsResponse")
    public com.hoau.how.module.itf.server.ws.claim.ResponseQueryClaims getClaims(
        @WebParam(name = "userID", targetNamespace = "")
        java.lang.String userID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findClaimsDetail", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.FindClaimsDetail")
    @WebMethod
    @ResponseWrapper(localName = "findClaimsDetailResponse", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.FindClaimsDetailResponse")
    public com.hoau.how.module.itf.server.ws.claim.ResponseQueryDetail findClaimsDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findClaimsPlace", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.FindClaimsPlace")
    @WebMethod
    @ResponseWrapper(localName = "findClaimsPlaceResponse", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.FindClaimsPlaceResponse")
    public java.util.List<com.hoau.how.module.itf.server.ws.claim.QueryCorpResult> findClaimsPlace(
        @WebParam(name = "billNo", targetNamespace = "")
        java.lang.String billNo,
        @WebParam(name = "billTel", targetNamespace = "")
        java.lang.String billTel
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "uploadClaims", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.UploadClaims")
    @WebMethod
    @ResponseWrapper(localName = "uploadClaimsResponse", targetNamespace = "http://hoauweb.ws.erry.com/", className = "com.hoau.how.module.itf.server.ws.claim.UploadClaimsResponse")
    public com.hoau.how.module.itf.server.ws.claim.ResponseClaimsObject uploadClaims(
        @WebParam(name = "claimsInfo", targetNamespace = "")
        com.hoau.how.module.itf.server.ws.claim.ClaimsInfo claimsInfo
    );
}
