
package com.hoau.wechat.ws.oms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-10-27T16:12:51.280+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class MobileServicePortType_MobileServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.mobile.interfaces.sinotrans.com", "MobileService");

    private MobileServicePortType_MobileServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MobileService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MobileService ss = new MobileService(wsdlURL, SERVICE_NAME);
        MobileServicePortType port = ss.getMobileServiceHttpPort();  
        
        {
        System.out.println("Invoking queryOrderDetail...");
        com.hoau.wechat.ws.oms.GetPhoneOrderReqModel _queryOrderDetail_in0 = null;
        com.hoau.wechat.ws.oms.GetPhoneOrderResModel _queryOrderDetail__return = port.queryOrderDetail(_queryOrderDetail_in0);
        System.out.println("queryOrderDetail.result=" + _queryOrderDetail__return);


        }
        {
        System.out.println("Invoking cancelPhoneOrde...");
        com.hoau.wechat.ws.oms.CancelOrderReqModel _cancelPhoneOrde_in0 = null;
        com.hoau.wechat.ws.oms.CancelOrderResModel _cancelPhoneOrde__return = port.cancelPhoneOrde(_cancelPhoneOrde_in0);
        System.out.println("cancelPhoneOrde.result=" + _cancelPhoneOrde__return);


        }
        {
        System.out.println("Invoking resetPwd...");
        com.hoau.wechat.ws.oms.ResetPwdReqModel _resetPwd_in0 = null;
        com.hoau.wechat.ws.oms.ResetPwdResModel _resetPwd__return = port.resetPwd(_resetPwd_in0);
        System.out.println("resetPwd.result=" + _resetPwd__return);


        }
        {
        System.out.println("Invoking loginByPhone...");
        com.hoau.wechat.ws.oms.LoginUserReqModel _loginByPhone_in0 = null;
        com.hoau.wechat.ws.oms.LoginUserResModel _loginByPhone__return = port.loginByPhone(_loginByPhone_in0);
        System.out.println("loginByPhone.result=" + _loginByPhone__return);


        }
        {
        System.out.println("Invoking updateCache...");
        com.hoau.wechat.ws.oms.UpdateCacheReqModel _updateCache_in0 = null;
        com.hoau.wechat.ws.oms.UpdateCacheResModel _updateCache__return = port.updateCache(_updateCache_in0);
        System.out.println("updateCache.result=" + _updateCache__return);


        }
        {
        System.out.println("Invoking queryOrder...");
        com.hoau.wechat.ws.oms.QueryOrdersReqModel _queryOrder_in0 = null;
        com.hoau.wechat.ws.oms.QueryOrdersResModel _queryOrder__return = port.queryOrder(_queryOrder_in0);
        System.out.println("queryOrder.result=" + _queryOrder__return);


        }
        {
        System.out.println("Invoking modifyOrder...");
        com.hoau.wechat.ws.oms.ModifyOrderReqModel _modifyOrder_in0 = null;
        com.hoau.wechat.ws.oms.ModifyOrderResModel _modifyOrder__return = port.modifyOrder(_modifyOrder_in0);
        System.out.println("modifyOrder.result=" + _modifyOrder__return);


        }
        {
        System.out.println("Invoking createOrder...");
        com.hoau.wechat.ws.oms.PhoneOrderReqModel _createOrder_in0 = null;
        com.hoau.wechat.ws.oms.PhoneOrderResModel _createOrder__return = port.createOrder(_createOrder_in0);
        System.out.println("createOrder.result=" + _createOrder__return);


        }
        {
        System.out.println("Invoking registerUser...");
        com.hoau.wechat.ws.oms.RegisterUserReqModel _registerUser_in0 = null;
        com.hoau.wechat.ws.oms.RegisterUserResModel _registerUser__return = port.registerUser(_registerUser_in0);
        System.out.println("registerUser.result=" + _registerUser__return);


        }

        System.exit(0);
    }

}
