package com.hoau.how.module.obh.server.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.hoau.how.module.obh.shared.domain.ContactsEntity;

@Repository
public interface ContactsEntityMapper {
    
	int deleteByPrimaryKey(@Param("contactsId")Long contactsId,@Param("userId")Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_shipper_address
     *
     * @mbggenerated Fri Jul 17 10:25:07 CST 2015
     */
    int insert(ContactsEntity record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_shipper_address
     *
     * @mbggenerated Fri Jul 17 10:25:07 CST 2015
     */
    ContactsEntity selectByPrimaryKey(@Param("ebsaId")Long ebsaId,@Param("modifier")Long modifier);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_shipper_address
     *
     * @mbggenerated Fri Jul 17 10:25:07 CST 2015
     */
    int updateByPrimaryKey(ContactsEntity record);
    
    List<ContactsEntity> queryMyContactsPage(@Param("contactsEntity")ContactsEntity contactsEntity,@Param("type")String type,
    		@Param("pageSize")int pageSize,@Param("offset")int offset);

    List<ContactsEntity> queryMyContacts(@Param("userId")long userId,@Param("type")String type);

    
	void setDefault(@Param("userId")long userId, @Param("contactsIds")long contactsIds);
	
	void setNotDefault(@Param("userId")long userId, @Param("contactsIds")long contactsIds,@Param("contactsType")String contactsType);
	
	int contactsTotals(@Param("userId")long userid,@Param("type")String type);
	
	List<ContactsEntity> findDefualt(@Param("userId")long userId,@Param("type")String type);
	
	ContactsEntity queryContact(ContactsEntity contact);

	String selectMobileById(@Param("id")Long id);
	
	
}