
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.how.module.itf.server.ws.waybilldetail;

import java.util.List;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-06-16T18:07:21.222+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WptServices",
                      portName = "WptServicesPort",
                      targetNamespace = "http://www.szzc.com.cn/services/WptServices",
//                      wsdlLocation = "http://10.39.109.29:8080/services/WptServices?wsdl",
                      wsdlLocation = "http://10.39.251.3:8080/hoaunew/services/WptServices?wsdl",
                      endpointInterface = "com.hoau.how.module.itf.server.ws.waybilldetail.WptServices")
                      
public class WptServicesPortImpl implements WptServices {

    private static final Logger LOG = Logger.getLogger(WptServicesPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.waybilldetail.WptServices#getWptYdInfo(java.util.List<java.lang.String>  arg0 )*
     */
    public java.util.List<WptYdInfo> getWptYdInfo(java.util.List<java.lang.String> arg0) { 
        LOG.info("Executing operation getWptYdInfo");
        System.out.println(arg0);
        try {
            java.util.List<com.hoau.how.module.itf.server.ws.waybilldetail.WptYdInfo> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	@Override
	public WaybillInfo queryOneWaybill(String arg0, String arg1) {
		 LOG.info("Executing operation queryOneWaybill");
	        System.out.println(arg0);
	        System.out.println(arg1);
	        try {
	            WaybillInfo _return = null;
	            return _return;
	        } catch (java.lang.Exception ex) {
	            ex.printStackTrace();
	            throw new RuntimeException(ex);
	        }
	}

}
