
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.how.module.itf.server.ws.dcpricetime;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-09-10T14:21:47.982+08:00
 * Generated source version: 3.0.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "HowPriceAndTimeQueryServices",
                      portName = "HowPriceAndTimeQueryServicesPort",
                      targetNamespace = "http://www.hoau.net/services/HowPriceAndTimeQueryServices",
                      wsdlLocation = "http://10.39.109.29:8080/services/HowPriceAndTimeQueryServices?wsdl",
                      endpointInterface = "com.hoau.how.module.itf.server.ws.dcpricetime.HowPriceAndTimeQueryServices")
                      
public class HowPriceAndTimeQueryServicesPortImpl implements HowPriceAndTimeQueryServices {

    private static final Logger LOG = Logger.getLogger(HowPriceAndTimeQueryServicesPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.how.module.itf.server.ws.dcpricetime.HowPriceAndTimeQueryServices#queryPriceAndTime(com.hoau.how.module.itf.server.ws.dcpricetime.PriceQueryVo  arg0 )*
     */
    public java.util.List<com.hoau.how.module.itf.server.ws.dcpricetime.PriceQueryResult> queryPriceAndTime(com.hoau.how.module.itf.server.ws.dcpricetime.PriceQueryVo arg0) { 
        LOG.info("Executing operation queryPriceAndTime");
        try {
            java.util.List<com.hoau.how.module.itf.server.ws.dcpricetime.PriceQueryResult> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
