
package com.hoau.wechat.ws.waybill;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-07-06T16:18:48.418+08:00
 * Generated source version: 3.0.2
 * 
 */
 
public class QuerySignInfoServices_QuerySignInfoServicesPort_Server{

    protected QuerySignInfoServices_QuerySignInfoServicesPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new QuerySignInfoServicesPortImpl();
        String address = "http://10.39.251.3:8080/hoaunew/services/QuerySignInfoServices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new QuerySignInfoServices_QuerySignInfoServicesPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
