
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.wechat.ws.waybill;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-07-06T16:18:48.400+08:00
 * Generated source version: 3.0.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "QuerySignInfoServices",
                      portName = "QuerySignInfoServicesPort",
                      targetNamespace = "http://www.hoau.net/services/QuerySignInfoServices",
                      wsdlLocation = "http://10.39.251.3:8080/hoaunew/services/QuerySignInfoServices?wsdl",
                      endpointInterface = "com.hoau.wechat.ws.waybill.QuerySignInfoServices")
                      
public class QuerySignInfoServicesPortImpl implements QuerySignInfoServices {

    private static final Logger LOG = Logger.getLogger(QuerySignInfoServicesPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.wechat.ws.waybill.QuerySignInfoServices#queryWaybill(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public com.hoau.wechat.ws.waybill.WaybillInfo queryWaybill(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation queryWaybill");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            com.hoau.wechat.ws.waybill.WaybillInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.wechat.ws.waybill.QuerySignInfoServices#querySignInfoServices(java.lang.String  arg0 )*
     */
    public com.hoau.wechat.ws.waybill.SignInfoEntity querySignInfoServices(java.lang.String arg0) { 
        LOG.info("Executing operation querySignInfoServices");
        System.out.println(arg0);
        try {
            com.hoau.wechat.ws.waybill.SignInfoEntity _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
